import type { ServiceId } from '../../config/services.ts';
export type ServicePresentation = { headline: string; summary: string; jobs: string[]; preparation: string; boundary: string; alt: string };
export const SERVICE_PRESENTATION: Record<ServiceId, ServicePresentation> = {
  handyman: { headline: 'A little help. A shorter home repair list.', summary: 'Doors, trim, mounting and the small repairs you have been meaning to get to. Start with your list; we will help sort out the right next step.', jobs: ['Doors and hardware','Trim and small repairs','Shelving and mounting','A list of odd jobs'], preparation: 'Share your repair list, a few photos and any parts you already have.', boundary: 'Electrical, plumbing and structural work may need a specialist rather than a handyman.', alt: 'Illustration of a finished oak door, brass hardware and fitted entry bench' },
  masonry: { headline: 'Make your steps and walkways welcoming again.', summary: 'Cracked brick, loose mortar or pavers that have settled? A5 helps you start a conversation with a local masonry professional.', jobs: ['Brick steps and stoops','Mortar and repointing','Walkways and pavers','Patios and low walls'], preparation: 'Photograph the whole area, the damage up close, and the side of any steps.', boundary: 'Significant movement or a leaning wall may need structural assessment before a repair is planned.', alt: 'Illustration of red brick steps with bluestone treads and a planted walkway' },
  landscaping: { headline: 'Bring your outdoor space back into shape.', summary: 'From overgrown beds to a yard that needs a fresh start, describe what you want to change and A5 will help coordinate the next step.', jobs: ['Seasonal yard cleanup','Planting and bed refreshes','Overgrowth and tidy-ups','Grading and surface water'], preparation: 'Include wide photos of the yard and explain where water collects, if relevant.', boundary: 'Drainage and excavation need a site assessment. Availability depends on the project and provider.', alt: 'Illustration of a suburban garden with hydrangeas and a curved planting bed' },
  painting: { headline: 'A fresh finish starts with the right preparation.', summary: 'Interior walls, exterior trim or paint that is peeling: tell us about the space and the finish you have in mind.', jobs: ['Interior rooms and trim','Exterior painting','Peeling paint and prep','Finishing after repairs'], preparation: 'Tell us which rooms or surfaces are involved, their condition and any known moisture issues.', boundary: 'Moisture, damaged surfaces and older paint may require additional assessment before painting.', alt: 'Illustration of a warm ivory living room with teal shelving' },
  drywall: { headline: 'Help your walls feel like home again.', summary: 'Holes, ceiling damage and recurring cracks deserve a closer look. A5 helps connect your repair with an appropriate local professional.', jobs: ['Wall holes and patches','Ceiling repairs','Cracks and damaged seams','Repairs after a resolved leak'], preparation: 'Show the damage and the surrounding wall or ceiling. Mention whether a leak has been fixed.', boundary: 'The cause of active water damage needs to be addressed before closing or refinishing a wall.', alt: 'Illustration of smooth finished walls and a sunlit ceiling' },
  tile: { headline: 'Small tile problems. A more finished space.', summary: 'Loose tile, cracked grout or a backsplash that needs attention. Share the details before deciding on a bigger renovation.', jobs: ['Cracked or loose tile','Grout repairs','Backsplashes','Floor and shower tile'], preparation: 'Photograph the affected area and tell us if matching spare tiles are available.', boundary: 'Shower leaks or movement under tile may need more than a surface repair.', alt: 'Illustration of sage bathroom tile with cream grout and brass fittings' },
  plumbing: { headline: 'Get everyday plumbing problems moving toward a fix.', summary: 'Running toilets, leaking fixtures and planned replacements. A5 reviews your request and helps coordinate the appropriate plumbing professional.', jobs: ['Toilets and fixtures','Leaks and supply lines','Faucets and sinks','Water heater requests'], preparation: 'Tell us where the problem is, when it started and whether water is currently leaking.', boundary: 'A5 is not an emergency dispatch service. For an immediate hazard, contact the appropriate emergency service or utility.', alt: 'Illustration of a kitchen faucet, white sink and warm wood counter' },
  electrical: { headline: 'A clear next step for lights, outlets and more.', summary: 'Describe the light, outlet or switch that needs attention. A5 helps coordinate an appropriate professional for scheduled electrical work.', jobs: ['Lights and fixtures','Outlets and switches','Ceiling fans','Electrical troubleshooting'], preparation: 'Describe what stopped working and any related symptoms. Photos should be taken from a safe distance.', boundary: 'Do not open electrical equipment. A5 is not emergency dispatch; immediate hazards need an emergency service or utility.', alt: 'Illustration of a brass wall light and white switches in a warm room' },
};
export const HOME_FAQ = [
 { question: 'Do I need to know which trade I need?', answer: 'No. Describe what is happening in your own words and choose “Not sure” in the request. A5 reviews the details to help identify the appropriate kind of professional.' },
 { question: 'Does A5 carry out the work?', answer: 'A5 reviews requests and coordinates introductions to local service providers. You discuss the scope, estimate, scheduling and terms of the work directly with the provider.' },
 { question: 'What happens after I send a request?', answer: 'A5 reviews the details and checks for an appropriate provider. Availability depends on the service, location and project. A request is not a confirmed appointment.' },
 { question: 'Can I send photos?', answer: 'Yes. You can attach up to five photos to help explain the project. They are optional and are not published on the website.' },
 { question: 'Can you help with an emergency?', answer: 'A5 is for project requests and scheduled work, not emergency dispatch. If there is an immediate danger, contact emergency services or the appropriate utility.' },
];
