import { rich, type ExpansionDraft } from "./types.ts";
export const GUIDE_DRAFTS: ExpansionDraft[] = [
 {
  key:"prepare-a-handyman-repair-list",type:"GUIDE",service:"handyman",title:"How to prepare a handyman repair list",description:"Turn scattered home repairs into a clear request: priorities, photos, materials and questions to ask before work begins.",question:"What should I include in a handyman request?",answer:"Group the tasks by room, identify the most important repair, and show each item with a photo and a short description. Note which materials you already have. Separate electrical, plumbing and structural concerns so the request can be reviewed for the appropriate trade.",sourceKeys:[],sections:[
   rich("Start with a useful list, not a diagnosis","A loose door handle, an unfinished strip of trim and a shelf still in its box can belong in one request. Describe the result you want for each item instead of prescribing a repair. ‘The bedroom door catches at the top’ gives the provider more useful information than ‘plane the door.’","Group tasks by room and number them. Mark anything affecting normal use of the home as a priority, then separate the improvements that can wait. A provider can use that order to discuss a realistic scope if the whole list cannot be completed in one visit."),
   rich("Show the task and its surroundings","Take a wide photo to show the location and a close-up to show the condition. For mounting work, include the item, its packaging or model information, and the intended wall. Describe any access limitation you already know about; do not open walls or remove covers to gather information.","List owner-supplied parts separately. Hardware that looks similar may have different dimensions or fixing requirements. Ask the provider to confirm suitability before you buy additional pieces."),
   rich("Agree on what the visit includes","Ask whether the proposal includes sourcing materials, removing old hardware, patching, painting and cleanup. If a repair reveals another problem, agree how additional work will be discussed before it starts. Keep the approved list available during the visit.","A long task list does not establish which trade should perform every item. Wiring, pipework and structural concerns should be identified explicitly when A5 reviews the request. A5 coordinates an introduction; the provider confirms scope, price and timing."),
   {type:"QUESTION_ANSWER",items:[{question:"Can I combine several small jobs?",answer:"Yes, describe them together and give each a priority. The provider will confirm which tasks fit the visit and whether another trade is needed."},{question:"Do I need to buy materials first?",answer:"Usually the useful first step is identifying what you already have and asking the provider what is suitable. Avoid ordering custom or nonreturnable items until the scope is confirmed."}]},
  ]
 },
 {
  key:"compare-masonry-repair-proposals",type:"GUIDE",service:"masonry",title:"How to compare masonry repair proposals",description:"Compare the scope behind masonry estimates: repair areas, base work, matching materials, access, cleanup and exclusions.",question:"How should I compare estimates for masonry repair?",answer:"Compare the work each proposal includes before comparing the price. Identify the exact repair area, any base or drainage work, material matching, removal and disposal, and the treatment of steps or railings. Ask each provider to explain assumptions and exclusions in writing.",sourceKeys:[],sections:[
   rich("Make sure the proposals address the same problem","One proposal may cover replacing visible mortar while another includes dismantling and rebuilding part of a stoop. Those are different projects even when they refer to the same entrance. Ask the provider to identify which sections will remain and which will be removed.","Use the same photos and project description for each discussion. Include previous repairs and any change you have noticed, such as a gap, tilt or loose tread. You do not need to decide on the repair method before asking for help."),
   rich("Ask what is included below and around the repair","If a proposal includes base work, ask where it extends and how that area will be restored. Discuss drainage observations, adjoining walks, railings, nearby planting and the point where the masonry meets the house. A provider should explain what can be assessed now and what may only become visible after removal.","Specify whether the proposal includes matching existing brick or stone, samples, salvage of usable pieces, disposal, and cleanup. A close visual match may matter more at the front entrance than in an inconspicuous area; tell the provider your priorities."),
   rich("Plan access and changes before work starts","Identify whether the entrance must remain usable and ask about the sequence of the work. Confirm who checks permit requirements and whether any railing or other trade work is included. Avoid treating a verbal schedule as a confirmed start date.","Ask how unexpected conditions will be documented and priced. Keep the agreed scope and any approved changes together so both sides can distinguish the original repair from additional work. A5 helps coordinate the introduction; the masonry provider assesses the structure and explains the proposed method."),
   {type:"COST_FACTORS",heading:"Items to compare line by line",factors:["Repair versus partial or complete rebuild","Size and limits of the work area","Base and drainage work included or excluded","Matching and replacing materials","Access, protection, disposal and restoration","Permit responsibilities and additional trade work"]},
  ]
 },
 {
  key:"plan-a-yard-cleanup-and-planting-project",type:"GUIDE",service:"landscaping",title:"Plan a yard cleanup and planting project",description:"Separate cleanup, planting and drainage concerns so your landscaping request has clear priorities and a useful scope.",question:"What should I include in a landscaping project brief?",answer:"Mark the areas to clean up, what should stay, what you want changed and how debris should be handled. For planting, describe the use of the space and your maintenance preferences. List standing water or grade changes separately so the provider can assess them before proposing work.",sourceKeys:[],sections:[
   rich("Separate the work into three decisions","Cleanup, planting and changing ground levels are different scopes. A cleanup list might include overgrowth, weeds, leaf debris and bed edges. A planting discussion should describe the effect you want: a clearer entrance, screening, seasonal color or less maintenance.","Identify plants and features you want to keep before discussing removal. If you do not know a plant's name, mark it in a photo. Ask the provider to review unclear items with you before work begins."),
   rich("Describe how the space behaves","Tell the provider how you use the yard and what you have observed after rain. Wide photos of the area and surrounding surfaces are more helpful than a close-up of a puddle alone. Note downspouts, paths and access gates without assuming which feature caused the problem.","Do not describe a water concern only as a request for more soil. Ask for the cause and proposed approach to be assessed. Ground-level changes, excavation and drainage work may involve requirements beyond ordinary planting; confirm the scope with the provider and relevant local office."),
   rich("Set practical expectations for the proposal","Discuss access, storage of materials, protection of retained plants and whether debris will be removed. Ask what restoration is included if equipment crosses a lawn or a bed is expanded. Establish the division between one-time work and ongoing care.","For new planting, ask for plant names, quantities, sizes and care instructions in the proposal. Share your willingness to water and maintain the area so the design can reflect it. Availability and timing should be confirmed for your request rather than assumed from a seasonal calendar."),
   {type:"QUESTION_ANSWER",items:[{question:"Should I request cleanup and drainage work together?",answer:"You can describe both in one request, but keep them as separate tasks. A provider can explain which work should happen first and whether additional assessment is needed."},{question:"What photos help?",answer:"Show the whole work area, the access route, features to keep and the specific issue. For water concerns, add observations about when the water appears."}]},
  ]
 },
 {
  key:"plan-a-painting-project",type:"GUIDE",service:"painting",title:"What to agree before a painting project",description:"Build a painting brief covering surfaces, preparation, finish, protection, access and older-paint questions before comparing proposals.",question:"What should a painting proposal include?",answer:"Identify the rooms or exterior surfaces, their condition, the preparation included and the finish you want. Agree on protection, repairs, materials, cleanup and touch-ups. If older painted surfaces will be disturbed, discuss lead-safe assessment and work practices before preparation begins.",sourceKeys:["epa"],sections:[
   rich("Define the surfaces, not just the room count","A room can include walls, ceilings, trim, doors and built-ins, but a quote may not include all of them. List the surfaces you want painted and distinguish color changes from repairs. Photograph peeling, staining and damaged areas so the provider can discuss preparation.","Tell the provider whether furniture will stay in the space and who will move it. For exterior work, identify landscaping, paths, neighboring access or other areas that need protection."),
   rich("Separate preparation from the finish","Ask which holes, seams, failed coatings or damaged trim are included. If there is a recurring stain or a known leak, explain it before discussing paint. Agree who assesses the underlying issue and whether another trade must finish before painting.","Specify the expected finish and ask how samples will be reviewed in the actual space. Confirm who supplies paint and whether leftover labeled material will be available for later touch-ups."),
   rich("Discuss older paint before disturbing it","EPA warns that work disturbing lead-based paint can create hazardous dust and recommends lead-safe certified contractors for renovation in pre-1978 homes. Tell the provider the home's approximate age and any known test results. Do not assume a fresh top coat establishes what is underneath.","Ask the provider how the work area will be contained and how the home will remain usable. The exact requirements depend on the property and scope; this planning guide does not determine which legal exceptions apply."),
   rich("Record the finish and handover","Agree on cleanup, disposal, access, and how completed work will be reviewed. Note any surfaces intentionally excluded and how additional preparation will be approved. A clear proposal makes comparisons more useful than a price attached only to a room name.","A5 can review the project details and coordinate a preferred local vendor. The painting provider confirms the preparation, materials, price and schedule for the actual property."),
  ]
 },
 {
  key:"plan-drywall-repair-after-a-leak",type:"GUIDE",service:"drywall",title:"Planning drywall repair after a leak",description:"Organize leak resolution, wall or ceiling assessment, access, finish matching and painting into a clear repair sequence.",question:"What should happen before damaged drywall is repaired?",answer:"Explain the leak history and confirm that the water source has been assessed before arranging the finish repair. The provider should assess the affected material, discuss whether other work is needed, and define the repair and painting scope. Photos alone cannot establish that a cavity is dry or sound.",sourceKeys:["moisture"],sections:[
   rich("Bring the history to the first conversation","Tell the provider when the stain or damage appeared, whether it changed after rain or fixture use, and what work has already been done. Include any plumber or roofer findings you have. Avoid describing a stain as resolved solely because it looks dry today.","Photograph the whole ceiling or wall and a closer view of the affected area from a safe position. Do not cut into the surface to provide a better photo. If the surface is sagging or there is an immediate hazard, keep clear and seek appropriate urgent assistance."),
   rich("Agree on assessment before the finish","Ask the provider how the material and surrounding area will be assessed and whether another specialist is needed. A cosmetic repair should not be used to hide a recurring issue. Conditions behind a wall may only become clear during assessment.","Identify any access opening needed for another trade and coordinate the order of those visits. If you want a removable access panel, discuss its location and appearance before the surface is closed."),
   rich("Define where the repair ends","A proposal should distinguish removing damaged material, replacing board, joint finishing, texture work, priming and painting. Ask whether the price includes finishing the whole ceiling or wall, or only the patched area.","Share any leftover paint details and your expectations for how the repair should look in daylight. Discuss furniture protection, dust management and cleanup. Do not assume that a drywall repair automatically includes a full room repaint."),
   rich("Keep the handoff simple","Keep the cause assessment and repair scope together. Identify who confirms the area is ready for the finishing trade, and ask how newly discovered damage changes the proposal. A5 can help route the request, but the relevant provider must assess the actual conditions.","When submitting the request, include the room, the visible damage, the leak history, any completed corrective work and whether you need painting included. Those details reduce repeated questions between trades."),
  ]
 },
 {
  key:"prepare-for-a-tile-repair",type:"GUIDE",service:"tile",title:"How to prepare for a tile repair",description:"Plan a tile repair around spare materials, the extent of damage, grout matching, access and the condition behind the visible finish.",question:"What information helps a provider assess a tile repair?",answer:"Show the whole tiled area and the damaged section, say whether tiles are loose or cracked, and mention any recurring moisture. Check for spare tiles and packaging, but let the provider assess compatibility. Ask whether the scope covers only the visible finish or also the underlying surface.",sourceKeys:[],sections:[
   rich("Separate appearance from a recurring problem","A missing grout joint, chipped tile and loose section of flooring need different conversations. Describe what changed and whether the same spot has been repaired before. Include water-related observations without assuming grout alone will address them.","For a shower or other wet area, ask the provider to assess whether the issue extends beyond the visible surface. A photograph cannot establish the condition of concealed materials or waterproofing."),
   rich("Find any spare material","Look for labeled boxes, leftover tile, grout records or purchase receipts. Photograph the front and any identifying packaging. A nominal size or similar color does not establish an exact match, so discuss samples before ordering a quantity.","If a close match cannot be found, ask about the visual alternatives before approving removal. Depending on the location, the discussion may include a larger replacement area or a deliberate change in finish rather than a small mismatched patch."),
   rich("Clarify removal, repair and finishing","Ask how much of the area will be opened, what underlying repair is included, and how unexpected conditions will be handled. Identify transitions, trim, fixtures and adjoining surfaces that might be affected.","Ask who moves fixtures, supplies materials and removes debris. If another trade is involved, agree on the sequence. A tile repair proposal should make it clear where the tile work ends and any plumbing or carpentry work begins."),
   rich("Plan for access and return to use","Tell the provider whether this is the home's only bathroom or a frequently used entrance. Ask when the surface can be used again for the actual products and method specified; avoid planning around a generic online drying time.","Share photos, dimensions if you have them, the spare material list and your finish priorities with A5. The provider can then confirm whether a targeted repair is practical and what needs to be assessed in person."),
  ]
 },
 {
  key:"prepare-for-a-plumbing-service-visit",type:"GUIDE",service:"plumbing",title:"Prepare for a scheduled plumbing visit",description:"Describe fixture problems clearly, gather useful product details and compare repair or replacement scopes before a scheduled plumbing visit.",question:"What should I send before a scheduled plumbing visit?",answer:"Identify the fixture or visible pipe, explain when the issue occurs and share photos without dismantling anything. Mention active water leakage, access limitations, previous repairs and any replacement product you have chosen. A5 reviews scheduled requests; it is not an emergency dispatch service.",sourceKeys:[],sections:[
   rich("Describe the behavior, not just the fixture","For a toilet, say whether it runs continuously, runs intermittently, leaks visibly or has another symptom. For a faucet, distinguish a drip from the outlet from water around the base or cabinet. Describe what you can observe safely rather than guessing which part failed.","State when the problem started and whether more than one fixture is affected. If water is actively causing damage or creating an immediate hazard, seek appropriate urgent assistance instead of waiting for a scheduled A5 request."),
   rich("Gather useful product and access details","Photograph the fixture and the surrounding space. Add model information or packaging you already have; there is no need to remove covers or disconnect anything to identify a part. Say whether the fixture is difficult to reach or whether furniture or stored items affect access.","If you are considering replacement, share the product before ordering. Ask the professional to confirm fit, connections and any additional work involved. A product described as a replacement may still have a different installation scope."),
   rich("Compare repair and replacement scopes","Ask the provider to explain the proposed work and which parts are included. A repair proposal and a replacement proposal are not directly comparable if one includes additional supply, drain or finish work.","Confirm who supplies the fixture, who handles removal and disposal, and whether associated wall, cabinet or tile repair is included. Ask who will determine applicable permit and inspection requirements for the actual scope."),
   rich("Agree on the next step","Keep the scope, assumptions and exclusions in writing. If access reveals another condition, ask how the provider will explain and obtain approval for additional work. Confirm scheduling with the provider after the introduction.","Your A5 request can start with the fixture, location, symptoms and optional photos. You do not need a technical diagnosis or a complete shopping list before getting help."),
  ]
 },
 {
  key:"plan-lighting-and-electrical-updates",type:"GUIDE",service:"electrical",title:"Plan a lighting or electrical service request",description:"Organize lighting, outlet and fan requests with clear symptoms, product details, access needs and questions for the electrical professional.",question:"What should I include in an electrical service request?",answer:"Describe the affected light, outlet, switch or fan and when the issue occurs. Share product details for planned replacements and note whether other devices are affected. Do not remove covers or test wiring for photos. The electrical professional determines the assessment and installation requirements.",sourceKeys:["esfi"],sections:[
   rich("Distinguish a repair from an upgrade","An existing light that stopped working and a new fixture in a new position are different requests. State which one you need and whether the existing controls are changing. If several devices are affected, include that observation rather than treating each as an unrelated repair.","If there is smoke, sparking, a burning smell or another immediate hazard, keep away and seek appropriate urgent assistance. A5 coordinates scheduled work and does not provide emergency dispatch."),
   rich("Share the product before the visit","For a new light or fan, include its model and installation information if available. Explain the intended location and whether the item has already been purchased. Let the professional assess support, controls, compatibility and the existing installation.","Photograph the area from a safe position. Do not remove an outlet cover, open equipment or expose wiring for the request. A wide room photo can help communicate access and location without creating an unnecessary task."),
   rich("Clarify what the installation includes","Ask whether the proposal includes removal, assembly, installation, testing and disposal. If the work involves a new location or access through a finished surface, ask what wall or ceiling repair is excluded and who will complete it.","Discuss how the provider will assess permit requirements and any inspections. Avoid assuming that a product change is automatically the same scope as the previous installation."),
   rich("Coordinate the room as well as the electrical work","Tell the provider about high ceilings, furniture, restricted access and other trades involved. Agree on product delivery and what must be ready before the visit. Have the intended fixture locations and control preferences documented.","A5 can review your request and coordinate an appropriate local professional. The professional confirms the work, required credentials, price and timing; a service page does not establish a booked appointment or specific availability."),
  ]
 },
];
