import { rich, type ExpansionDraft } from "./types.ts";
export const LOCAL_DRAFTS: ExpansionDraft[] = [
 {key:"florham-park-handyman",type:"SERVICE_LOCATION",service:"handyman",town:"florham-park",title:"Handyman services in Florham Park, NJ",description:"Plan a Florham Park repair visit for doors, trim, hardware and mounting. Organize your task list and request a preferred local vendor through A5.",question:"Can I combine several small repairs in a Florham Park service request?",answer:"Yes. Send one prioritized list with the rooms, tasks and optional photos. A5 reviews the work and helps coordinate a suitable local provider. Identify electrical, plumbing or structural concerns separately so the request can be directed to the appropriate trade.",sourceKeys:["florham"],sections:[
  rich("One list for the repairs around your home","Start with the door that catches, the loose handle or the unfinished trim. Group the items by room and mark which ones affect everyday use. A small task can be hard to explain in isolation, so include a wider photo showing where the item sits in the room.","For a Florham Park visit, share access arrangements and whether you have already bought hardware or mounting equipment. A list helps the provider discuss what can be completed together; it does not establish that every task belongs to the same trade."),
  rich("Confirm the scope before adding more work","A useful proposal separates labor, parts, sourcing and any finish repair. Ask whether a mounting job includes assembly or whether replacing trim includes painting. List supplied materials so the provider can assess them before the visit.","If the request grows into an alteration, have the provider check whether a municipal review is needed. Florham Park's permitting page is the official starting point for applications and inspection instructions; a handyman label alone does not determine the requirements."),
  rich("Prepare for a productive visit","Clear access to the agreed work areas and keep the approved list available. Identify the items that must be completed first if parts, access or additional assessment affect the scope. Agree how unexpected work will be discussed before it starts.","Submit the list to A5 with your Florham Park address details and preferred timing. A5 coordinates the introduction; the provider confirms the estimate, scope and schedule after reviewing your request."),
 ]},
 {key:"florham-park-painting",type:"SERVICE_LOCATION",service:"painting",town:"florham-park",title:"Painting services in Florham Park, NJ",description:"Request painting in Florham Park with a clear plan for rooms, trim, preparation and finish. A5 helps coordinate a preferred local vendor.",question:"What should I include in a Florham Park painting request?",answer:"List the rooms or exterior surfaces, describe peeling, stains or damage, and say whether ceilings, doors and trim are included. Mention older painted surfaces and known moisture issues before preparation starts. Photos help a provider distinguish finishing work from repairs that need attention first.",sourceKeys:["florham","epa"],sections:[
  rich("Define the surfaces and the result you want","For an interior refresh, list the rooms and whether each includes walls, ceilings, trim or doors. For exterior work, identify the surfaces and show access around the house. Describe the result you want without assuming every wall needs the same preparation.","A Florham Park painting request can combine several areas, but distinguish the priority spaces from optional additions. That helps the provider explain the sequence and limits of a proposal."),
  rich("Resolve preparation questions first","Share stains, peeling and previous repairs in the first conversation. Ask who assesses moisture or damaged material before painting, and whether drywall or carpentry work is included. Preparation should be a stated part of the scope rather than an assumption attached to a color choice.","For a pre-1978 home, discuss lead-safe assessment before disturbing painted surfaces. EPA recommends lead-safe certified contractors for this work. If the project expands beyond painting, consult Florham Park's permitting information about the actual alteration."),
  rich("Plan protection and completion","Agree on moving furniture, protecting plants or flooring, selecting samples and storing materials. Confirm who supplies paint and how touch-ups and cleanup will be handled. Share access constraints before scheduling.","A5 reviews the request and helps coordinate a preferred local vendor. The provider confirms what preparation is needed, what the price includes and when work can take place."),
 ]},
 {key:"madison-masonry",type:"SERVICE_LOCATION",service:"masonry",town:"madison",title:"Masonry services in Madison, NJ",description:"Plan masonry repairs in Madison for brick steps, mortar and walks. Compare repair scopes, prepare useful photos and request local help through A5.",question:"How do I start a masonry repair request in Madison?",answer:"Show the whole set of steps, walk or wall and a close-up of the damage. Explain whether anything is loose, leaning or separating and mention previous repairs. A5 reviews the request; the masonry provider assesses whether targeted repair or more extensive work is appropriate.",sourceKeys:["madison"],sections:[
  rich("Start with the entrance or walk as a whole","A close-up of missing mortar tells only part of the story. Include the whole entrance, a side view and where the masonry meets adjoining surfaces. Describe what has changed: a loose tread, a gap, a low spot or an area that has been patched before.","For a Madison entrance project, tell the provider whether another entrance is available during the work. Identify railings, adjoining paths and planting that may affect access or restoration. Keep clear of visibly unstable areas rather than testing them for the request."),
  rich("Compare the repair area, not only the total price","Ask the provider to distinguish replacing individual materials, repointing and rebuilding a section. Discuss what base work or adjoining repair is included and how matching brick or stone will be approached. Different scopes can produce very different proposals for the same steps.","Before work begins, agree who checks applicable construction requirements. Madison's Building Department is the official local contact. Provide the proposed scope instead of assuming a repair or a rebuild has the same requirements."),
  rich("Make the proposal easy to review","Ask for the limits of removal, disposal, protection and restoration in writing. If the plan includes railing work or another trade, identify who coordinates it. Discuss how newly exposed conditions will be documented and priced.","Send A5 the location, photos, what you noticed and your preferred timing. A5 helps coordinate a local vendor; the provider assesses the work and confirms the proposal and schedule."),
 ]},
 {key:"madison-plumbing",type:"SERVICE_LOCATION",service:"plumbing",town:"madison",title:"Plumbing services in Madison, NJ",description:"Request scheduled plumbing help in Madison for toilets, faucets and fixture projects. Prepare symptoms, photos and replacement details for provider review.",question:"Can A5 help arrange a scheduled plumbing visit in Madison?",answer:"A5 can review a request for a running toilet, leaking fixture or planned replacement and help coordinate an appropriate local professional. Include the symptoms and whether water is actively leaking. Immediate hazards require urgent assistance; A5 is not an emergency dispatch service.",sourceKeys:["madison"],sections:[
  rich("Describe the symptom before choosing a replacement","A running toilet, water around a faucet and a planned sink replacement are different scopes. Say where the problem appears and when it happens. Mention previous repair attempts and whether more than one fixture is affected.","For a Madison plumbing request, show the fixture and surrounding space without dismantling anything. Include model details or product packaging you already have. The professional can determine what needs to be assessed in person."),
  rich("Coordinate fixtures and surrounding finishes","If you are replacing a fixture, have the provider review the product before ordering. Ask whether the work includes removal, connections and disposal, and what wall, cabinet or tile repair is excluded. A supplied fixture does not automatically make the job a direct swap.","Ask the professional to confirm permit and inspection responsibilities for the proposed work. Madison's Building Department provides the local construction contact; the scope, rather than the product name, is the useful starting point for that discussion."),
  rich("Prepare access and the handoff","Identify access limitations and whether the fixture is the only one available in the home. Discuss the expected interruption and work sequence directly with the provider. Keep the agreed scope and any changes in writing.","A5 can begin with a short description, your Madison location and optional photos. Scheduling and pricing are confirmed after review, not when the online request is sent."),
 ]},
 {key:"chatham-electrical",type:"SERVICE_LOCATION",service:"electrical",town:"chatham",title:"Electrical services in Chatham, NJ",description:"Plan scheduled electrical work in Chatham for lighting, outlets and fans. Confirm Borough or Township, product details and the scope before the visit.",question:"What does A5 need for an electrical request in Chatham?",answer:"Describe the light, outlet, switch or fan and say whether it is a repair or planned change. Include your address and whether the property is in Chatham Borough or Chatham Township. Those are separate municipalities, so the professional should confirm the correct construction contact for the work.",sourceKeys:["chathamBorough","chathamTownship","madison","esfi"],sections:[
  rich("Separate repairs from planned lighting changes","A light that stopped working needs an assessment; moving a fixture or adding a fan needs a defined installation scope. Say which situation applies and whether other devices are affected. Share product information for an upgrade without opening electrical equipment for photos.","If there is smoke, sparking or another immediate hazard, seek appropriate urgent assistance. A5 handles scheduled requests and does not provide emergency dispatch."),
  rich("Confirm Borough or Township","Chatham Borough and Chatham Township have separate construction arrangements. Madison's Building Department serves Chatham Borough, while Chatham Township lists its own construction contact. Include the full property location so the provider can confirm the relevant office.","Discuss permit and inspection responsibilities against the actual proposal. Do not rely only on a Chatham mailing address to decide where project questions belong."),
  rich("Account for fixtures, access and finish repair","Share the fixture model, intended location, ceiling access and any furniture that affects the work area. Ask whether removal, assembly, testing and disposal are included. If work opens a wall or ceiling, agree who handles the finish repair.","A5 helps coordinate a preferred local provider after reviewing the request. The electrical professional confirms suitability, scope, price and timing for the property."),
 ]},
 {key:"chatham-tile",type:"SERVICE_LOCATION",service:"tile",town:"chatham",title:"Tile services in Chatham, NJ",description:"Plan tile and grout repair in Chatham around matching materials, moisture observations, access and Borough or Township project contacts.",question:"Can a small tile repair be assessed before replacing a larger area?",answer:"A provider can assess whether a targeted repair is practical after reviewing the damage, available matching material and underlying conditions. Send the whole tiled area, a close-up and any spare tile information. Recurring moisture or loose tiles should be discussed before treating the issue as cosmetic.",sourceKeys:["chathamBorough","chathamTownship","madison"],sections:[
  rich("Start with the area, the damage and any spare tile","Identify whether the request concerns a floor, backsplash or shower. Show the whole surface and the affected section, and explain whether the issue is new or recurring. Look for spare tiles, grout records or packaging before buying replacements.","For a Chatham bathroom project, say whether the space must stay usable during the work. A provider can discuss options for a small repair, but a close-up cannot establish what is happening behind the finish."),
  rich("Clarify the scope around the tile","Ask whether the proposal includes removal, substrate assessment, trim, grout and disposal. If fixtures must be moved or another trade is needed, distinguish that work from the tile scope. Agree how additional conditions will be reviewed before work expands.","If the project becomes a renovation, confirm whether the property is in Chatham Borough or Township. The Borough points to Madison's Construction Department; the Township has a separate construction contact. The provider should check the actual work with the appropriate office."),
  rich("Discuss matching and return to use","Share your preference for a close match or a deliberate change in finish. Ask about samples before ordering a large quantity. Discuss access, protection of adjoining surfaces and when the area can return to use for the proposed method.","Send A5 the Chatham location, photos and what you hope to achieve. A5 coordinates the introduction; the provider confirms the repair approach, estimate and schedule."),
 ]},
 {key:"morris-township-landscaping",type:"SERVICE_LOCATION",service:"landscaping",town:"morris-township",title:"Landscaping services in Morris Township, NJ",description:"Organize a Morris Township yard project around cleanup, planting and water concerns. Define priorities and request a preferred local vendor through A5.",question:"How should I separate yard cleanup from a drainage concern?",answer:"List cleanup and planting tasks separately from standing water or proposed grade changes. Show the wider area, access route and where water appears. A provider should assess the cause and proposed scope before work is described simply as adding soil or refreshing a bed.",sourceKeys:["morris"],sections:[
  rich("Build a clear yard-work brief","Mark the beds, boundaries and features you want to keep. Separate removal, cleanup and new planting, and identify your main goal: easier maintenance, a clearer entrance or a more usable outdoor area. Photos can show the intended work without requiring plant names.","For a Morris Township request, include access through gates, material storage and how debris should be handled. Those details help a provider distinguish the visible planting area from the practical work needed to complete it."),
  rich("Treat changes to the ground as a separate scope","If water collects or a surface slopes in an unwanted direction, record what you observe after rain. Show downspouts, adjoining paving and nearby structures. Ask for an assessment before approving a change in ground levels.","Morris Township's Building Department publishes construction guidance and a portal for property and permit information. Have the provider confirm which local reviews apply if the proposal expands into drainage, structures or other regulated work."),
  rich("Agree on restoration and ongoing care","Ask how equipment access will be protected and what lawn or bed restoration is included. For planting, discuss sizes, quantities and the care you are prepared to provide. Separate a one-time project from any recurring maintenance arrangement.","A5 reviews the project and helps coordinate a local vendor. Share the Morris Township location and priorities; the provider confirms the site assessment, price and timing."),
 ]},
 {key:"morris-township-drywall",type:"SERVICE_LOCATION",service:"drywall",town:"morris-township",title:"Drywall services in Morris Township, NJ",description:"Request drywall and ceiling repair in Morris Township. Plan around damage history, access, finish matching and painting responsibilities.",question:"What should I send for a Morris Township drywall repair?",answer:"Show the whole wall or ceiling and the damaged section, describe how it happened, and mention leaks or previous repairs. Say whether painting is needed. If water caused the damage, the source and affected materials need assessment before the finish repair is planned.",sourceKeys:["morris","moisture"],sections:[
  rich("Explain what happened before the patch","A hole from a moved fixture and a recurring ceiling stain require different conversations. Include the history of the damage and any corrective work already completed. Show the area from a safe position without opening the surface for the request.","For a Morris Township repair after another trade's visit, identify any access that still needs to remain open. Agree on the sequence before arranging a finish repair that might have to be reopened."),
  rich("Define the finish you expect","Ask whether the proposal includes board replacement, joint finishing, texture, primer and painting. Explain whether you want the whole wall or ceiling refinished or only the damaged area addressed. Include any existing paint details you have.","If the work extends into a broader alteration, the Township's Building Department is the local construction contact. The provider should confirm the requirements for the actual scope rather than assuming all wall work is the same."),
  rich("Coordinate protection and completion","Discuss furniture access, dust management, cleanup and how work will be reviewed. If hidden conditions are discovered, agree that the provider will explain the change before adding work. Photos help communicate the problem but cannot establish concealed conditions.","A5 can review the request and coordinate an appropriate local vendor. Include the location, damage history, photos and whether painting should be part of the proposal."),
 ]},
 {key:"morristown-masonry",type:"SERVICE_LOCATION",service:"masonry",town:"morristown",title:"Masonry services in Morristown, NJ",description:"Plan masonry work in Morristown for walks, pavers, mortar and steps. Clarify access, repair limits and restoration before requesting a local provider.",question:"What helps a provider assess a Morristown walkway or paver repair?",answer:"Show the entire route, the uneven or damaged area and adjoining surfaces. Describe where water collects and whether the surface has been repaired before. Ask the provider to distinguish resetting or replacing visible material from any base work included in the proposal.",sourceKeys:["morristown"],sections:[
  rich("Look beyond the single uneven piece","A walkway repair needs a clear picture of the whole route. Include where it meets the entrance, driveway or adjoining patio, and show the low or uneven area. Describe what changed over time without assuming which material or method is needed.","For a Morristown property, identify the access route and any space limitations for materials or debris. Say whether the path is the main entrance so the provider can discuss how the work affects access."),
  rich("Separate surface work from a larger rebuild","Ask the provider to explain the limits of removal and whether the proposal includes base work. Discuss reusing existing pavers, matching replacement material and restoring adjoining planting or lawn. These choices affect the scope even when the visible repair looks small.","Morristown's construction office offers help determining permit requirements. Describe the planned work and ask about any other required review before approving an expanded scope; do not assume the word repair settles that question."),
  rich("Agree on the handover","Confirm disposal, cleanup and any adjoining finish work in the proposal. If railings or steps are involved, clarify whether their assessment and work are included. Ask how unexpected conditions will be documented before additional work is approved.","Send the photos and Morristown location to A5. A5 coordinates the introduction; the provider assesses the site and confirms the repair method, estimate and schedule."),
 ]},
 {key:"morristown-painting",type:"SERVICE_LOCATION",service:"painting",town:"morristown",title:"Painting services in Morristown, NJ",description:"Plan a Morristown painting project with clear preparation, surface and access details. Request a preferred local vendor through A5.",question:"How do I prepare an exterior painting request in Morristown?",answer:"Identify the surfaces, show peeling or damaged areas and describe access around the property. Separate paint preparation from repairs to trim or other materials. Discuss older-paint concerns before disturbing coatings, and confirm any local review needed if the scope changes beyond painting.",sourceKeys:["morristown","epa"],sections:[
  rich("Show the preparation the project may need","Photograph each side or surface you want included, then add closer views of peeling, staining or damaged trim. State whether doors, shutters, railings or other details are part of the request. An exterior project should not be defined only by the size of the house.","For interior work in Morristown, the same principle applies: list walls, ceilings, doors and trim separately. Tell the provider which rooms need to remain usable and whether furniture can be moved."),
  rich("Resolve repair and older-paint questions","Ask which surface repairs are included and whether another trade needs to assess damaged material or a recurring moisture issue. Discuss the preparation method and protection of surrounding areas before comparing finish coats or colors.","EPA recommends lead-safe certified contractors for renovation, repair and painting in pre-1978 homes. Share the home's age and known paint information. If the proposal becomes a broader alteration, confirm applicable review with Morristown's construction office."),
  rich("Make access and completion part of the scope","Describe restrictions on access, storage and neighboring space. Agree on protection, cleanup and where samples will be reviewed. Confirm who supplies materials and how final touch-ups will be handled.","A5 reviews the project details and helps coordinate a preferred local vendor. The provider confirms the preparation, estimate and timing for the actual property, including any conditions that affect the work."),
 ]},
 {key:"east-hanover-landscaping",type:"SERVICE_LOCATION",service:"landscaping",town:"east-hanover",title:"Landscaping services in East Hanover, NJ",description:"Plan East Hanover cleanup, planting and yard improvements. Separate maintenance from earthwork and clarify the scope before requesting a provider.",question:"What should I clarify before a yard project involving earthwork in East Hanover?",answer:"Describe whether the project is cleanup, planting or a change to ground levels. East Hanover's construction page identifies grading approval before a building permit when earthwork is involved. Confirm which reviews apply to the actual proposal before work begins; not every yard task has the same scope.",sourceKeys:["eastHanover"],sections:[
  rich("Start with the purpose of the yard project","Tell the provider whether you want overgrowth cleared, beds refreshed, planting added or a water concern assessed. Mark the areas and existing features that should stay. A cleanup request is different from altering where water travels or changing the shape of the ground.","For an East Hanover request, include the route into the yard and what access is available for materials. State whether debris should be removed and whether planting choices should prioritize a lower-maintenance routine."),
  rich("Check the review path before changing the ground","East Hanover's Construction Department publishes grading and zoning information. For a proposal involving earthwork, discuss the grading approval requirement and any related reviews with the provider and relevant office before scheduling.","Show where water appears and the adjoining surfaces, but do not prescribe adding soil as the solution. Ask the provider to assess the site and explain the limits of the proposed work. An online description cannot establish site levels or concealed conditions."),
  rich("Separate the project from its aftercare","Ask for removal, new materials, cleanup and restoration to be itemized. If new plants are included, discuss their identity, size, placement and care. Agree who handles lawn or bed restoration along the access route.","A5 can review the East Hanover project and coordinate a local introduction. The provider confirms site suitability, the proposal and availability after review."),
 ]},
 {key:"east-hanover-plumbing",type:"SERVICE_LOCATION",service:"plumbing",town:"east-hanover",title:"Plumbing services in East Hanover, NJ",description:"Plan scheduled plumbing repairs and fixture replacements in East Hanover with clear symptoms, access details and scope questions.",question:"How do I plan a fixture replacement in East Hanover?",answer:"Share the existing fixture, the proposed replacement and any access limitations before ordering or scheduling. Ask the professional to confirm fit, connections, surrounding finish work and permit or inspection responsibilities. A5 coordinates scheduled requests; the provider confirms the actual installation scope.",sourceKeys:["eastHanover"],sections:[
  rich("Distinguish a repair from a replacement project","A leaking faucet may start as a repair discussion, while replacing a sink can affect connections, cabinetry and finishes. Describe the outcome you want and whether you have bought a replacement. Include product details so the provider can review compatibility.","For an East Hanover service request, mention when the issue occurs and whether water is actively leaking. A5 is not emergency dispatch; immediate hazards should be addressed through appropriate urgent assistance."),
  rich("Clarify inspection and other work","Ask who will check the permit requirements and arrange applicable inspections. East Hanover publishes plumbing inspection information through its Construction Department. Confirm current arrangements for your project instead of assuming a general visit schedule is a booking.","Have the provider identify excluded wall, tile or cabinet work. If another trade is needed, agree on the sequence and who coordinates it. A fixture price alone does not describe the cost or scope of the complete installation."),
  rich("Prepare for the visit","Show the fixture and surrounding area without dismantling equipment. Identify stored items or other obstacles affecting access, and say whether this is the only available fixture of its kind in the home. Discuss interruptions directly with the provider.","A5 can begin with the location, a short description and optional photos. The professional assesses the work, confirms the estimate and agrees the schedule after the introduction."),
 ]},
];
