export const EXPANSION_SOURCES = {
  esfi: {title:"ESFI Electrical Safety Dos",url:"https://www.esfi.org/electrical-safety-dos/",publisher:"Electrical Safety Foundation International",claim:"Electrical warning signs warrant inspection by a qualified electrician."},
  moisture: {title:"EPA mold cleanup guidance",url:"https://www.epa.gov/mold/what-are-basic-mold-cleanup-steps",publisher:"U.S. Environmental Protection Agency",claim:"Address water problems rather than covering affected materials with a finish."},
  madison: {title:"Madison Building & Construction Department",url:"https://www.rosenet.org/153/Building-Construction-Department",publisher:"Borough of Madison",claim:"Madison's Building Department covers Madison and Chatham Borough. Use the department for project-specific construction questions."},
  florham: {title:"Florham Park permitting",url:"https://www.florhamparknj.gov/Permitting",publisher:"Borough of Florham Park",claim:"Florham Park provides permit submission information and inspection request instructions; inspection requests identify the permit, address, inspection type and contact."},
  chathamBorough: {title:"Chatham Borough planning, zoning and construction",url:"https://www.chathamborough.org/departments/construction",publisher:"Borough of Chatham",claim:"Chatham Borough has its own planning/zoning information and links to the Madison Construction Department and its permit portal."},
  chathamTownship: {title:"Chatham Township construction",url:"https://chathamtownship.org/directory/construction/",publisher:"Chatham Township",claim:"Chatham Township lists a separate construction contact for permits and inspections."},
  morris: {title:"Morris Township building and construction",url:"https://www.morristwp.com/121/Building",publisher:"Morris Township",claim:"Morris Township's Building Department handles construction permits and inspections. Its page links to its SDL portal and permit guidance."},
  morristown: {title:"Morristown building and construction",url:"https://www.townofmorristown.org/building",publisher:"Town of Morristown",claim:"Morristown's construction office can help determine permit requirements; its building page describes permits, inspections and prior approvals."},
  eastHanover: {title:"East Hanover Construction Department",url:"https://www.easthanovertownship.com/Departments/construction-department",publisher:"Township of East Hanover",claim:"East Hanover's construction page states grading approval precedes a building permit when earthwork is involved. It publishes zoning information and separate inspection schedules."},
  epa: {title:"EPA Lead Renovation, Repair and Painting Program",url:"https://www.epa.gov/lead/lead-renovation-repair-and-painting-program",publisher:"U.S. Environmental Protection Agency",claim:"Disturbing lead-based paint can create hazardous dust. EPA recommends lead-safe certified contractors for renovation, repair or painting in pre-1978 homes."},
} as const;
