import Link from 'next/link';
import {notFound} from 'next/navigation';
import {SERVICES} from '@config/services';
import {MUNICIPALITIES} from '@config/locations';
import {COUNTIES} from '@config/counties';
import {AdminPageHeader} from '@/components/admin/AdminPageHeader';
import {SubmitButton} from '@/components/admin/SubmitButton';
import {loadVendorSignup} from '@/lib/vendor-signup/admin';
import {reviewVendorSignup} from '@/lib/vendor-signup/review-action';
import {loadVendors} from '@/lib/admin/vendors';
import {formatAdminDateTime} from '@/lib/admin/format';
import styles from '@/components/admin/admin.module.css';
export default async function SignupReview({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string;saved?:string}>}){
 const {id}=await params,row=await loadVendorSignup(id);if(!row)notFound();
 const p=await searchParams,data=row.payload,vendors=row.status==='PENDING'?await loadVendors():[];
 const matches=vendors.filter(v=>v.email?.trim().toLowerCase()===data.email||v.businessName.trim().toLowerCase()===data.businessName.toLowerCase());
 return <><AdminPageHeader title={data.businessName} description={`Vendor signup · ${row.status} · ${formatAdminDateTime(row.created_at)} UTC`} actions={<Link className={styles.secondaryButton} href="/admin/vendors/signups">Signups</Link>}/>{p.error&&<p role="alert" className={styles.flashError}>{p.error}</p>}{p.saved&&<p role="status" className={styles.flashNotice}>Review saved.</p>}
 <section className={styles.panel}><h2>1. Review submitted information</h2><dl><dt>Contact</dt><dd>{data.contactName} · <a href={`mailto:${data.email}`}>{data.email}</a>{data.phone&&` · ${data.phone}`}</dd>{data.website&&<><dt>Website</dt><dd><a href={data.website} target="_blank" rel="noopener noreferrer">{data.website}</a></dd></>}<dt>Services</dt><dd>{SERVICES.filter(s=>data.serviceIds.includes(s.id)).map(s=>s.name).join(', ')}</dd></dl><p className={styles.mutedCopy}>All selected services apply across these towns. Exceptions are notes for manual assignment.</p>{COUNTIES.map(c=>{const towns=MUNICIPALITIES.filter(t=>t.countyId===c.id&&data.locationIds.includes(t.id));return towns.length>0&&<details key={c.id}><summary>{c.name} · {towns.length} towns</summary><p>{towns.map(t=>t.name).sort().join(', ')}</p></details>;})}{data.notes&&<p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{data.notes}</p>}<p className={styles.mutedCopy}>Permission to receive signup and project emails recorded {formatAdminDateTime(row.consented_at)} UTC · consent text version {row.consent_version}. This is self-reported information, not verified credentials.</p></section>
 {row.status==='PENDING'?<section className={styles.panel}><h2>2. Check existing vendors</h2>{matches.length?<><p>Matching name or email found. Review the existing record before linking.</p><ul>{matches.map(v=><li key={v.id}><Link href={`/admin/vendors/${v.id}`}>{v.businessName}</Link> · {v.email??'No email'}</li>)}</ul></>:<p>No exact name or email match. Check the vendor list for spelling variations before creating a new record.</p>}<h2>3. Record the decision</h2><form action={reviewVendorSignup} className={styles.formGrid}><input type="hidden" name="signupId" value={id}/><label className={styles.fieldLabel}>Action<select name="action" defaultValue={matches.length?'link':'create'}><option value="create">Create vendor from signup</option><option value="link">Link to existing vendor</option><option value="dismiss">Dismiss signup</option></select></label><label className={styles.fieldLabel}>Existing vendor (for linking)<select name="vendorId" defaultValue={matches.length===1?matches[0].id:''}><option value="">Choose an existing vendor</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.businessName} · {v.email??'No email'}</option>)}</select></label><label className={styles.fieldLabel}>Review note (optional)<textarea name="note" maxLength={1000} rows={3}/></label><p className={styles.mutedCopy}>Create saves a DISCOVERED vendor with the submitted services and towns, ready for manual assignment by email. Link records the relationship only: contact details, coverage and status are preserved. Make any needed updates in the existing vendor editor. Neither action sends email.</p><SubmitButton className={styles.primaryButton} pendingLabel="Saving…">Save decision</SubmitButton></form></section>:<section className={styles.panel}><h2>Review recorded</h2><p>{row.reviewed_at&&formatAdminDateTime(row.reviewed_at)} UTC · {row.status}</p>{row.review_note&&<p>{row.review_note}</p>}{row.vendor_id&&<Link className={styles.primaryButton} href={`/admin/vendors/${row.vendor_id}`}>Open vendor record</Link>}</section>}</>;
}
