import {test} from 'node:test';
import assert from 'node:assert/strict';
import {loadOpportunity} from '../src/lib/opportunity/load.ts';
import {createOpportunityToken} from '../src/lib/opportunity/token.ts';
import {validateReport,connectionState,type NetworkReport,acceptanceHours} from '../src/lib/network/policy.ts';
import {vendorEvidence,recommendation,type NetworkAssignment} from '../src/lib/network/evidence.ts';
import {networkQueue} from '../src/lib/network/queue.ts';
import {buildVendorOpportunityEmail} from '../src/lib/opportunity/email.ts';
const token=createOpportunityToken().raw;
function client(status='ASSIGNED',revoked=false,expires='2099-01-01T00:00:00Z',due='2099-01-01T00:00:00Z'){
 const calls:string[]=[];
 const db={from(table:string){let selection='';const q={select(s:string){selection=s;calls.push(`${table}:${s}`);return q;},eq(){return q;},order(){calls.push('photos queried');return Promise.resolve({data:[{id:'photo',storage_bucket:'lead-uploads',storage_path:'secret'}],error:null});},maybeSingle(){let data:unknown=null;if(table==='assignment_capabilities')data={assignment_id:'a',expires_at:expires,revoked_at:revoked?'2026-01-01':null};if(table==='lead_assignments')data={id:'a',lead_id:'l',status,acceptance_due_at:due};if(table==='leads')data=selection.includes('customers')?{project_description:'Secret address 123 Main, email private@example.invalid',customers:{full_name:'Private Name',phone:'555-555-5555',email:'private@example.invalid',preferred_contact_method:'email'}}:{service_id:'handyman',location_id:'florham-park',urgency:'EXPLORING'};return Promise.resolve({data,error:null});}};return q;},storage:{from(){return{async createSignedUrl(){calls.push('signed URL');return{data:{signedUrl:'https://example.invalid/secret'},error:null};}};}}};return{db:db as unknown as Parameters<typeof loadOpportunity>[1],calls};
}
test('unaccepted opportunity never queries raw description, customers or photo storage',async()=>{const{db,calls}=client();const view=await loadOpportunity(token,db);assert.equal(view.access,'open');assert.ok(!calls.some(c=>/customers|project_description|photos|signed URL/.test(c)));assert.doesNotMatch(JSON.stringify(view),/Private Name|123 Main|private@example|secret/);});
test('only accepted assignment unlocks full request and signed photos',async()=>{const{db,calls}=client('ACCEPTED');const view=await loadOpportunity(token,db);assert.equal(view.access,'accepted');assert.ok(calls.includes('signed URL'));assert.match(JSON.stringify(view),/Private Name/);});
for(const [status,revoked,expires,due] of [['CANCELLED',false,'2099-01-01','2099-01-01'],['ACCEPTED',true,'2099-01-01','2099-01-01'],['ACCEPTED',false,'2000-01-01','2099-01-01'],['ASSIGNED',false,'2099-01-01','2000-01-01'],['PASSED',false,'2099-01-01','2099-01-01']] as const)test(`stale access ${status}/${revoked}/${expires}/${due} loads no protected data`,async()=>{const{db,calls}=client(status,revoked,expires,due);const view=await loadOpportunity(token,db);assert.ok(['unavailable','passed'].includes(view.access));assert.ok(!calls.some(c=>/customers|project_description|photos|signed URL/.test(c)));});
test('invalid capability makes no database calls',async()=>{const{db,calls}=client();assert.equal((await loadOpportunity('wrong',db)).access,'unavailable');assert.equal(calls.length,0);});
const assignment:NetworkAssignment={id:'a',lead_id:'l',vendor_id:'v',status:'ACCEPTED',assigned_at:'2026-01-01',accepted_at:'2026-01-02',notification_sent_at:'2026-01-01',notification_status:'SENT',acceptance_due_at:'2026-01-02'};
const report:NetworkReport={id:'r',assignment_id:'a',party:'HOMEOWNER',contact:'YES',outcome:'COMPLETED',rating:5,note:'Original',help_requested:false,created_at:'2026-01-03',disputed:false,excluded:false};
test('only accepted homeowner completed-work confirmation permits rating',()=>{assert.ok(validateReport({...report},'HOMEOWNER',true).ok);for(const [party,accepted,outcome,contact]of [['VENDOR',true,'COMPLETED','YES'],['HOMEOWNER',false,'COMPLETED','YES'],['HOMEOWNER',true,'ESTIMATE','YES'],['HOMEOWNER',true,'COMPLETED','NO']] as const)assert.equal(validateReport({...report,outcome,contact},party,accepted).ok,false);assert.equal(validateReport({...report,rating:null},'HOMEOWNER',false).ok,false);});
test('missing responses are unknown and vendor-only completion never produces ratings',()=>{const e=vendorEvidence('v',[assignment],[{...report,party:'VENDOR',rating:null}]);assert.equal(e.reviewCount,0);assert.equal(e.completed,0);assert.equal(e.failedContact,0);assert.equal(e.unknownContact,1);assert.equal(recommendation(e,true,true).tier,1);});
test('latest report wins without reviving excluded older evidence',()=>{const newer={...report,id:'new',created_at:'2026-01-04',excluded:true};assert.equal(vendorEvidence('v',[assignment],[report,newer]).reviewCount,0);});
test('conflict or dispute excludes rating; source notes remain untouched',()=>{const vendor={...report,id:'v',party:'VENDOR' as const,contact:'NO',outcome:'DID_NOT_PROCEED',rating:null};assert.equal(connectionState([report,vendor],true),'Reports need review');assert.equal(vendorEvidence('v',[assignment],[report,vendor]).reviewCount,0);assert.equal(vendorEvidence('v',[assignment],[{...report,disputed:true}]).reviewCount,0);assert.equal(report.note,'Original');});
test('five answered observations needed; many missing do not reduce contact rate',()=>{const assignments=Array.from({length:30},(_,i)=>({...assignment,id:`a${i}`}));const reports=assignments.slice(0,5).map((a,i)=>({...report,id:`r${i}`,assignment_id:a.id}));const e=vendorEvidence('v',assignments,reports);assert.equal(e.unknownContact,25);assert.equal(recommendation(e,true,true).tier,0);assert.equal(recommendation({...e,contactResponses:4},true,true).tier,1);assert.equal(recommendation(e,false,true).tier,3);});
test('queue keeps expired offers and failed/aging connections actionable without autoassign',()=>{const now='2026-02-01';assert.equal(networkQueue([{...assignment,status:'ASSIGNED'}],[],[],now)[0].action,'Release expired offer');assert.equal(networkQueue([assignment],[],[],now)[0].action,'Check homeowner connection');assert.equal(networkQueue([assignment],[{...report,contact:'NO',outcome:'PENDING',rating:null}],[],now)[0].action,'Connection needs follow-up');assert.equal(networkQueue([assignment],[report],[],now).length,0);});
test('acceptance window is bounded and email distinguishes deadline from access expiry',()=>{assert.equal(acceptanceHours('0'),24);assert.equal(acceptanceHours('73'),24);assert.equal(acceptanceHours('12'),12);const e=buildVendorOpportunityEmail({serviceLabel:'Handyman',locationLabel:'Florham Park',timingLabel:'Exploring',photoCount:1,opportunityUrl:'https://example.invalid/opportunity',acceptanceHours:24});assert.match(e.text,/within 24 hours/);assert.match(e.text,/expires after 72 hours/);assert.match(e.text,/after acceptance/);});

test('delivery failures remain actionable and retries use per-invitation idempotency',async()=>{
 const {sendNetworkCheckin}=await import('../src/lib/network/checkin.ts');
 for(const [error,expected]of [['provider_unreachable','UNCERTAIN'],['provider_503','UNCERTAIN'],['provider_422','FAILED'],['','SENT']]){
  const calls:{name:string;args:Record<string,unknown>}[]=[];
  const db={rpc:async(name:string,args:Record<string,unknown>)=>{calls.push({name,args});return{data:name==='admin_prepare_network_checkin'?[{ok:true,recipient:'fixture@example.invalid',invitation_id:'invite'}]:true,error:null};}} as unknown as NonNullable<Parameters<typeof sendNetworkCheckin>[4]>['db'];
  await sendNetworkCheckin('a','HOMEOWNER','operator',false,{db,send:async message=>{assert.equal(message.idempotencyKey,'a5-checkin-invite');assert.equal(message.to,'fixture@example.invalid');assert.match(message.html,/<a href="https:\/\/www.a5homeservices.com\/check-in\//);assert.doesNotMatch(message.text,/Private Name|123 Main/);return error?{ok:false,error}:{ok:true};}});
  assert.equal(calls[1].args.p_status,expected);assert.equal(String(calls[0].args.p_token_hash).length,64);
 }
});
test('missing permission or recipient never sends an email',async()=>{const{sendNetworkCheckin}=await import('../src/lib/network/checkin.ts');let sent=false;const db={rpc:async()=>({data:[{ok:false,error_code:'homeowner_checkin_not_permitted'}],error:null})}as unknown as NonNullable<Parameters<typeof sendNetworkCheckin>[4]>['db'];const r=await sendNetworkCheckin('a','HOMEOWNER','operator',false,{db,send:async()=>{sent=true;return{ok:true};}});assert.equal(r.ok,false);assert.equal(sent,false);});
test('check-in capability derives party and assignment without loading customer data',async()=>{
 const{loadCheckin}=await import('../src/lib/network/checkin.ts');const previous=process.env.ENABLE_NETWORK_FOLLOWUP;process.env.ENABLE_NETWORK_FOLLOWUP='true';
 try{for(const party of ['HOMEOWNER','VENDOR']){const calls:string[]=[];const db={from(table:string){const q={select(s:string){calls.push(`${table}:${s}`);return q;},eq(){return q;},async maybeSingle(){return{data:table==='network_invitations'?{id:'invite',assignment_id:'a',party,expires_at:'2099-01-01',revoked_at:null,status:'SENT'}:null,error:null};},async single(){return{data:table==='lead_assignments'?{accepted_at:'2026-01-01',lead_id:'l',vendors:{business_name:'Fixture'}}:{service_id:'handyman',location_id:'florham-park',checkins_stopped_at:null},error:null};}};return q;}}as unknown as Parameters<typeof loadCheckin>[1];const result=await loadCheckin(token,db);assert.equal(result?.party,party);assert.ok(!calls.some(c=>/customers|project_description|project_photos|token_hash|recipient/.test(c)));}}
 finally{if(previous===undefined)delete process.env.ENABLE_NETWORK_FOLLOWUP;else process.env.ENABLE_NETWORK_FOLLOWUP=previous;}
});

test('audited content edits preserve layout topology and linked sources',async()=>{
 const{readFileSync}=await import('node:fs');const{createHash}=await import('node:crypto');const raw=readFileSync(new URL('../content/network/copy-updates.json',import.meta.url),'utf8');const edits=JSON.parse(raw),manifest=JSON.parse(readFileSync(new URL('../docs/network/CONTENT-MANIFEST.json',import.meta.url),'utf8'));
 assert.equal(createHash('sha256').update(raw).digest('hex'),manifest.sha256);assert.equal(edits.length,288);assert.equal(edits.filter((e:{indexable:boolean})=>e.indexable).length,78);
 const links=(x:unknown):unknown[]=>{if(Array.isArray(x))return x.flatMap(links);if(x&&typeof x==='object')return Object.entries(x).flatMap(([k,v])=>['href','sourceIds','sourceId','source_id','url'].includes(k)?[[k,v]]:links(v));return[];};
 for(const e of edits){assert.deepEqual(Object.keys(e.after).sort(),['title','h1','meta_description','direct_answer','sections'].sort());assert.deepEqual(e.before.sections.map((s:{type:string})=>s.type),e.after.sections.map((s:{type:string})=>s.type));assert.deepEqual(links(e.before),links(e.after));assert.doesNotMatch(JSON.stringify(e.after),/preferred local|A5 (?:can )?coordinates|provider availability is checked individually/);}
});
