import Link from 'next/link';
import {redirect} from 'next/navigation';
import {resolveAdminAccess} from '@/lib/admin/authorize';
import {AdminPageHeader} from '@/components/admin/AdminPageHeader';
import {loadWorkQueue} from '@/lib/admin/work-queue-data';
import {formatAdminDateTime} from '@/lib/admin/format';
import styles from '@/components/admin/admin.module.css';
export default async function WorkQueuePage({searchParams}:{searchParams:Promise<{view?:string;page?:string}>}){
 const access=await resolveAdminAccess(); if(!access.ok)redirect('/admin/login');
 const params=await searchParams;const queue=await loadWorkQueue();const view=params.view==='vendors'?'vendors':'requests';const all=queue[view];
 const requested=Number(params.page);const page=Number.isSafeInteger(requested)&&requested>0?Math.min(requested,Math.max(1,Math.ceil(all.length/40))):1;const rows=all.slice((page-1)*40,page*40);
 return <><AdminPageHeader title="Work queue" description="Kevin’s next steps for requests and provider follow-up. Alerts go to hello@a5homeservices.com; review as requests arrive."/><nav className={styles.filters} aria-label="Work queue views"><Link className={view==='requests'?styles.primaryButton:styles.secondaryButton} href="/admin/queue" aria-current={view==='requests'?'page':undefined}>Requests · {queue.requests.length}</Link><Link className={view==='vendors'?styles.primaryButton:styles.secondaryButton} href="/admin/queue?view=vendors" aria-current={view==='vendors'?'page':undefined}>Vendor tasks · {queue.vendors.length}</Link></nav><p className={styles.mutedCopy}>{view==='requests'?'Delivery problems and due follow-ups come first, followed by review, assignment and project progress. Forwarded leads and future follow-ups appear last.':'Review new vendor signups and find or correct missing business emails. Public business contacts can receive assigned free leads without prior vendor confirmation or an availability check.'}</p>{!rows.length?<p className={styles.empty}>No open {view==='requests'?'requests':'vendor tasks'} in this view.</p>:<div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Item</th><th>Next action</th><th>Details</th><th>Recorded / follow-up · UTC</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td data-label="Item"><Link href={row.href}>{row.title}</Link></td><td data-label="Next action"><Link href={row.href}>{row.action}</Link></td><td data-label="Details">{row.detail}</td><td data-label="Recorded / follow-up">{row.since?formatAdminDateTime(row.since):'Email needed'}</td></tr>)}</tbody></table></div>}<nav className={styles.filters} aria-label="Work queue pages">{page>1&&<Link href={`/admin/queue?view=${view}&page=${page-1}`}>Previous</Link>}<span>Page {page} of {Math.max(1,Math.ceil(all.length/40))} · {all.length} items</span>{page*40<all.length&&<Link href={`/admin/queue?view=${view}&page=${page+1}`}>Next</Link>}</nav></>;
}
