import {loadNetworkData,loadNetworkPermission,loadReviewEvents,networkSnapshotTime} from '@/lib/network/data';
import {networkAdminAction} from '@/lib/network/actions';
import {connectionState} from '@/lib/network/policy';
import {formatAdminDateTime} from '@/lib/admin/format';
import {SubmitButton} from '@/components/admin/SubmitButton';
import styles from '@/components/admin/admin.module.css';
import type {NetworkAssignment} from "@/lib/network/evidence";
import type {NetworkReport} from "@/lib/network/policy";
import type {NetworkInvitation} from "@/lib/network/data";
export async function NetworkPanel({leadId}:{leadId:string}){
 if(process.env.ENABLE_NETWORK_FOLLOWUP!=='true')return null;
 const {assignments,reports,invitations}=await loadNetworkData(leadId),permission=await loadNetworkPermission(leadId);
 const events=await loadReviewEvents(reports.map(r=>r.id)),now=networkSnapshotTime();
 return <NetworkPanelView leadId={leadId} assignments={assignments} reports={reports} invitations={invitations} permission={permission} events={events} now={now}/>;
}
export function NetworkPanelView({leadId,assignments,reports,invitations,permission,events,now}:{leadId:string;assignments:NetworkAssignment[];reports:NetworkReport[];invitations:NetworkInvitation[];permission:Awaited<ReturnType<typeof loadNetworkPermission>>;events:Awaited<ReturnType<typeof loadReviewEvents>>;now:number}){
 return <section id="network" className={styles.section}><h2 className={styles.sectionTitle}>4. Connection & feedback</h2><p className={styles.mutedCopy}>A sent offer, provider acceptance, homeowner contact and completed work are separate events. Check-ins send only when you choose; no automatic redistribution.</p>
 {(!permission.network_consent_version||permission.checkins_stopped_at)&&<div className={styles.panel}><h3>{permission.checkins_stopped_at?'Homeowner stopped check-in emails':'Homeowner check-in permission not recorded'}</h3><p>Do not email a check-in until the homeowner has requested follow-up. Record an actual conversation or written request below; this is not a substitute for obtaining permission.</p><form action={networkAdminAction} className={styles.form}><input type="hidden" name="leadId" value={leadId}/><input type="hidden" name="action" value="permission"/><label className={styles.fieldLabel}>When and how permission was obtained<textarea name="reason" required maxLength={1000}/></label><label className={styles.checkLabel}><input type="checkbox" name="homeownerRequested" required/>The homeowner explicitly requested these project follow-up emails.</label><SubmitButton>Record permission</SubmitButton></form></div>}
 {!assignments.length&&<p className={styles.empty}>Assign an opportunity to begin tracking the connection.</p>}
 {assignments.map(a=>{const rows=reports.filter(r=>r.assignment_id===a.id),history=invitations.filter(i=>i.assignment_id===a.id).sort((x,y)=>y.created_at.localeCompare(x.created_at));const open=['ASSIGNED','ACCEPTED'].includes(a.status);return <div className={styles.panel} key={a.id}><h3>{a.status==='ASSIGNED'?(a.acceptance_due_at&&Date.parse(a.acceptance_due_at)<=now?'Offer expired':'Offered'):a.status==='PASSED'?'Declined':a.status==='CANCELLED'?'Closed / released':connectionState(rows,!!a.accepted_at)}</h3><p className={styles.mutedCopy}>{a.vendor_name??'Provider assignment'} · {a.id.slice(0,8)} · {formatAdminDateTime(a.assigned_at)}{a.acceptance_due_at&&<> · Accept by {formatAdminDateTime(a.acceptance_due_at)}</>}</p>
 {open&&<><div className={styles.formGrid}>{(['HOMEOWNER','VENDOR'] as const).map(party=>{const last=history.find(i=>i.party===party),blocked=party==='HOMEOWNER'?(!permission.network_consent_version||!!permission.checkins_stopped_at):!a.accepted_at;return <form action={networkAdminAction} className={styles.form} key={party}><input type="hidden" name="leadId" value={leadId}/><input type="hidden" name="assignmentId" value={a.id}/><input type="hidden" name="action" value="send"/><input type="hidden" name="party" value={party}/><h4>{party==='HOMEOWNER'?'Homeowner check-in':'Provider progress update'}</h4><p className={styles.mutedCopy}>{last?`Last delivery: ${last.status} · ${formatAdminDateTime(last.sent_at??last.created_at)}`:'Not sent yet.'}</p>{last&&['SENDING','UNCERTAIN'].includes(last.status)&&<label className={styles.checkLabel}><input type="checkbox" name="retryUncertain"/>I inspected the previous delivery and want a replacement link. The previous link will be revoked.</label>}{blocked?<p className={styles.mutedCopy}>{party==='HOMEOWNER'?'Permission required, or check-ins are stopped.':'Available after provider acceptance.'}</p>:<SubmitButton pendingLabel="Sending…">Send {party==='HOMEOWNER'?'homeowner':'provider'} check-in</SubmitButton>}</form>;})}</div>
 <details className={styles.secondaryDetails}><summary>{a.status==='ACCEPTED'?'Recover an accepted connection':'Release an expired offer'}</summary><p>Revoke this provider’s secure access and return the request to Qualified. You must choose the next provider yourself. Information already viewed cannot be recalled.</p><form action={networkAdminAction} className={styles.form}><input type="hidden" name="leadId" value={leadId}/><input type="hidden" name="assignmentId" value={a.id}/><input type="hidden" name="action" value="release"/><label className={styles.fieldLabel}>Reason for another introduction<textarea name="reason" maxLength={1000} required/></label>{a.status==='ACCEPTED'&&<label className={styles.checkLabel}><input type="checkbox" name="homeownerRequested" required/>I confirmed that the homeowner wants another provider and recorded that conversation in the reason.</label>}<SubmitButton>Release assignment for manual fallback</SubmitButton></form></details></>}
 <details className={styles.secondaryDetails}><summary>Feedback history ({rows.length})</summary>{rows.length===0?<p>No reports yet. Outcome is unknown.</p>:rows.sort((x,y)=>y.created_at.localeCompare(x.created_at)).map(r=><div key={r.id} className={styles.panel}><p><strong>{r.party==='HOMEOWNER'?'Homeowner':'Provider'}</strong> · {formatAdminDateTime(r.created_at)} · Contact: {r.contact} · {r.outcome.replaceAll('_',' ')}{r.rating!==null&&` · ${r.rating}/5 stars`}{r.disputed&&' · DISPUTED'}{r.excluded&&' · EXCLUDED FROM SUGGESTIONS'}</p><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{r.note}</p>{r.help_requested&&<p>Homeowner requested contact about another introduction.</p>}<form action={networkAdminAction} className={styles.form}><input type="hidden" name="leadId" value={leadId}/><input type="hidden" name="action" value="moderate"/><input type="hidden" name="reportId" value={r.id}/><label className={styles.fieldLabel}>Evidence review<select name="decision"><option value="DISPUTE">Flag for review; exclude from suggestions</option><option value="EXCLUDE">Exclude invalid evidence</option><option value="RESTORE">Restore valid evidence</option></select></label><label className={styles.fieldLabel}>Reason (required; preserves original feedback)<input name="reason" required maxLength={1000}/></label><SubmitButton>Record evidence decision</SubmitButton></form>{events.filter(e=>e.report_id===r.id).map(e=><p className={styles.mutedCopy} key={e.id}>{formatAdminDateTime(e.created_at)} · {e.action} · {e.reason} · operator {e.actor_user_id.slice(0,8)}</p>)}</div>)}</details>
 <details className={styles.secondaryDetails}><summary>Check-in delivery history ({history.length})</summary>{history.map(i=><p key={i.id}>{i.party} · {i.status} · {formatAdminDateTime(i.created_at)}{i.revoked_at?' · link replaced':''}{i.error_code?` · ${i.error_code}`:''}</p>)}</details>
 </div>;})}</section>;
}
