import Link from 'next/link';
import {loadNetworkData} from '@/lib/network/data';
import {vendorEvidence,recommendation} from '@/lib/network/evidence';
import type {VendorCoverage} from '@/lib/admin/vendors';
import styles from '@/components/admin/admin.module.css';
export async function VendorSuggestions({vendors,serviceId,locationId}:{vendors:VendorCoverage[];serviceId:string|null;locationId:string|null}){
 if(process.env.ENABLE_NETWORK_FOLLOWUP!=='true')return null;
 const {assignments,reports}=await loadNetworkData();
 const ranked=vendors.map(v=>{const evidence=vendorEvidence(v.id,assignments,reports);return{vendor:v,evidence,suggestion:recommendation(evidence,!!serviceId&&v.serviceIds.includes(serviceId),!!locationId&&v.locationIds.includes(locationId))};}).sort((a,b)=>a.suggestion.tier-b.suggestion.tier||a.vendor.businessName.localeCompare(b.vendor.businessName));
 return <details className={styles.secondaryDetails} open><summary>Provider suggestions & evidence</summary><p className={styles.mutedCopy}>Coverage first, then homeowner-confirmed contact evidence with at least five answered check-ins. Showing up to eight suggestions; the assignment menu retains all eligible providers. Metrics describe all recorded services, not competence in a particular trade. Unanswered check-ins are unknown. Ratings are descriptive and do not drive automatic assignment. You can choose any email-present provider in the assignment control.</p><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Provider / reason</th><th>Offers & acceptance</th><th>Homeowner contact</th><th>Completed-work reviews</th></tr></thead><tbody>{ranked.slice(0,8).map(({vendor:v,evidence:e,suggestion:s})=><tr key={v.id}><td data-label="Provider / reason"><Link href={`/admin/vendors/${v.id}`}>{v.businessName}</Link><p><strong>{s.label}</strong></p><p>{s.reason}</p></td><td data-label="Offers & acceptance">{e.accepted}/{e.offered} accepted{e.medianAcceptanceHours!==null&&<p>Median {e.medianAcceptanceHours.toFixed(1)} hours to accept</p>}</td><td data-label="Homeowner contact">{e.contacted}/{e.contactResponses} confirmed<p>{e.failedContact} no contact · {e.unknownContact} unknown</p></td><td data-label="Completed-work reviews">{e.averageStars===null?'No ratings':`${e.averageStars.toFixed(1)}/5 · ${e.reviewCount} reviews`}<p>{e.completed} homeowner-reported completions</p><Link href={`/admin/vendors/${v.id}#network-evidence`}>Inspect requests</Link></td></tr>)}</tbody></table></div></details>;
}
