/** Authored pages only. Does not enumerate or publish service/location permutations. */
import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';
import{MUNICIPALITIES}from'../config/locations.ts';import{COUNTIES,countyPath}from'../config/counties.ts';
import{buildContentPathFromRecord}from'../src/lib/authority/urls.ts';import{validateForPublication}from'../src/lib/authority/validate.ts';
import type{ContentPageRecord,ContentSection,SourceRecord,ContentSourceLink,ContentRelationship}from'../src/lib/authority/types.ts';
import type{LocalTown}from'../content/local-depth/plan.ts';
const read=(p:string)=>JSON.parse(readFileSync(p,'utf8'));
const batch=process.argv[2];if(!/^\d{2}$/.test(batch??''))throw Error('Use a two-digit batch number');
const base=`content/town-profiles/batch-${batch}`;const docs=`docs/town-profiles/batch-${batch}`;const privateDir=`.wrangler/town-profiles/batch-${batch}`;
const queue=read('docs/town-profiles/QUEUE.json').towns as {id:string;batch:number}[];const expected=queue.filter(t=>t.batch===Number(batch)).map(t=>t.id);if(!expected.length)throw Error('Unknown batch');const before=read(`${privateDir}/before.json`) as {content_pages:ContentPageRecord[];sources:SourceRecord[];content_sources:ContentSourceLink[];content_relationships:ContentRelationship[]};
const towns=read(`${base}.json`) as LocalTown[];
if(towns.length!==expected.length||new Set(towns.map(t=>t.location)).size!==towns.length||towns.some(t=>!expected.includes(t.location)))throw Error('Batch does not match approved queue');
const updates:ContentPageRecord[]=[],sources:SourceRecord[]=[],sourceLinks:ContentSourceLink[]=[],relationships:ContentRelationship[]=[];
const stamp=new Date().toISOString();
const uid=(url:string)=>{const s=createHash('sha256').update('a5-town-profiles:'+url).digest('hex');return `${s.slice(0,8)}-${s.slice(8,12)}-4${s.slice(13,16)}-8${s.slice(17,20)}-${s.slice(20,32)}`;};
for(const local of towns){const old=before.content_pages.find(p=>p.page_type==='LOCATION'&&p.primary_location_id===local.location);const town=MUNICIPALITIES.find(t=>t.id===local.location);if(!old||!town||old.indexable)throw Error('Expected existing noindex municipal profile: '+local.location);const county=COUNTIES.find(c=>c.id===town.countyId)!;
 const sections:ContentSection[]=[{type:'RICH_TEXT',heading:local.heading,paragraphs:local.paragraphs},{type:'RICH_TEXT',heading:`Prepare your ${town.name} project`,paragraphs:[],items:local.projects.map(p=>({title:p.title,body:p.body,links:[{label:`Explore ${p.service.replaceAll('-',' ')} projects`,href:`/services/${p.service}`}]}))},{type:'QUESTION_ANSWER',items:[{question:local.question,answer:local.response},{question:`How does A5 help with my ${town.name} request?`,answer:'Describe the work and share your contact details. A5 reviews the request and forwards it to an independent professional whose recorded service and geographic coverage match. The professional discusses the estimate, scope and schedule with you directly. Sending a request does not book work.'}]},{type:'RICH_TEXT',heading:'Your project location',paragraphs:[`${town.name} is in ${county.name}. Use the work municipality and ZIP code when submitting your request, even if a mailing address uses a different place name.`],links:[{label:`Explore ${county.name}`,href:countyPath(county)}]},{type:'SOURCE_LIST',heading:'Official local resources used in this guide'},{type:'CTA',title:`Start your ${town.name} project`,description:'One clear request helps us make the right introduction. Agree on the work directly with your independent professional.',primaryLabel:'Request service'}];
 updates.push({...old,meta_description:local.description,direct_answer:local.answer,sections,indexable:true});
 for(const ref of local.sources){let s=before.sources.find(s=>s.url===ref.url)||sources.find(s=>s.url===ref.url);if(!s){s={id:uid(ref.url),title:ref.title,url:ref.url,publisher:ref.publisher,source_type:'GOVERNMENT',retrieved_at:stamp,reviewed_at:stamp};sources.push(s);}if(!before.content_sources.some(l=>l.content_page_id===old.id&&l.source_id===s!.id))sourceLinks.push({content_page_id:old.id,source_id:s.id,relationship_type:'SUPPORTS'});}
 const countyPage=before.content_pages.find(p=>p.page_type==='CORE'&&p.slug===county.slug)!;
 if(!before.content_relationships.some(r=>r.from_page_id===countyPage.id&&r.to_page_id===old.id))relationships.push({from_page_id:countyPage.id,to_page_id:old.id,relationship_type:'RELATED'});
}
for(const p of updates){p.reviewed_by='Codex / owner-authorized SEO editorial review';p.reviewed_at=stamp;p.last_reviewed_at=stamp;const v=validateForPublication({page:p});if(!v.valid)throw Error(`${p.slug}: ${JSON.stringify(v.issues)}`);}
const manifest={updates,sources,sourceLinks,relationships};const raw=JSON.stringify(manifest,null,2)+'\n';writeFileSync(`${base}.manifest.json`,raw);
writeFileSync(`${docs}.review.json`,JSON.stringify({sha256:createHash('sha256').update(raw).digest('hex'),pages:updates.map(p=>({id:p.id,path:buildContentPathFromRecord(p),newlyIndexable:towns.some(t=>t.location===p.primary_location_id)&&p.page_type==='LOCATION',purpose:towns.find(t=>t.location===p.primary_location_id)?.focus??'Missing purpose',sourceClaims:towns.find(t=>t.location===p.primary_location_id)?.sources??before.content_sources.filter(s=>s.content_page_id===p.id).map(l=>before.sources.find(s=>s.id===l.source_id))}))},null,2)+'\n');console.log({updates:updates.length,newlyIndexable:towns.length,sources:sources.length,relationships:relationships.length});
