/** Guarded, exact authored updates. Dry-run unless --apply; never blindly rerun a receipt. */
import{readFileSync,writeFileSync,existsSync}from'node:fs';import{createHash}from'node:crypto';import{getSupabaseAdmin}from'../src/lib/supabase/admin.ts';import{validateForPublication}from'../src/lib/authority/validate.ts';import type{ContentPageRecord,SourceRecord,ContentSourceLink,ContentRelationship}from'../src/lib/authority/types.ts';
const raw=readFileSync('content/seo-readiness/manifest.json','utf8');const m=JSON.parse(raw) as {updates:ContentPageRecord[];sources:SourceRecord[];sourceLinks:ContentSourceLink[];relationships:ContentRelationship[]};
const hash=createHash('sha256').update(raw).digest('hex');if(hash!==JSON.parse(readFileSync('docs/seo-readiness/CONTENT-REVIEW.json','utf8')).sha256)throw Error('Unreviewed manifest');
if(new URL(process.env.NEXT_PUBLIC_SUPABASE_URL!).hostname!=='hfzzudrukeshkzsqhwsg.supabase.co')throw Error('Wrong project');
const db=getSupabaseAdmin();const live=await db.from('content_pages').select('*').in('id',m.updates.map(p=>p.id));if(live.error||live.data.length!==m.updates.length)throw Error('Incomplete preflight');
for(const p of m.updates){if(!validateForPublication({page:p}).valid)throw Error('Invalid page');const old=live.data.find(r=>r.id===p.id);if(old.updated_at!==p.updated_at||old.status!=='PUBLISHED')throw Error('Concurrent change: '+p.slug);}
console.log({preflight:'passed',updates:m.updates.length,newSources:m.sources.length,sha256:hash});if(!process.argv.includes('--apply'))process.exit(0);
const prefix='.wrangler/seo-readiness/content';if(existsSync(prefix+'-receipt.json'))throw Error('Prior receipt: inspect before resume');writeFileSync(prefix+'-release-before.json',JSON.stringify(live.data),{flag:'wx',mode:0o600});
const receipt:{sha256:string;started:string;intent:unknown;writes:unknown[];completed?:string}={sha256:hash,started:new Date().toISOString(),intent:null,writes:[]};const save=()=>writeFileSync(prefix+'-receipt.json',JSON.stringify(receipt,null,2),{mode:0o600});save();
for(const[table,rows]of[['sources',m.sources],['content_sources',m.sourceLinks],['content_relationships',m.relationships]]as const){if(!rows.length)continue;receipt.intent={table,count:rows.length};save();const r=await db.from(table).insert(rows as Record<string,unknown>[]).select();if(r.error||r.data.length!==rows.length)throw Error('Failed or uncertain '+table+':'+r.error?.code);receipt.writes.push({table,count:rows.length});receipt.intent=null;save();}
for(const p of m.updates){receipt.intent={table:'content_pages',id:p.id};save();const stamp=new Date().toISOString();const r=await db.from('content_pages').update({sections:p.sections,direct_answer:p.direct_answer,meta_description:p.meta_description,indexable:p.indexable,reviewed_by:p.reviewed_by,reviewed_at:stamp,last_reviewed_at:stamp,updated_at:stamp}).eq('id',p.id).eq('updated_at',p.updated_at).select('id,updated_at');if(r.error||r.data.length!==1)throw Error('Failed/concurrent '+p.slug);receipt.writes.push(r.data[0]);receipt.intent=null;save();}receipt.completed=new Date().toISOString();save();console.log({completed:receipt.completed,writes:receipt.writes.length});
