/** Guarded, exact authored updates. Dry-run unless --apply; never blindly rerun a receipt. */
import{readFileSync,writeFileSync,existsSync}from'node:fs';import{createHash}from'node:crypto';import{getSupabaseAdmin}from'../src/lib/supabase/admin.ts';import{validateForPublication}from'../src/lib/authority/validate.ts';import type{ContentPageRecord,SourceRecord,ContentSourceLink,ContentRelationship}from'../src/lib/authority/types.ts';
const batch=process.argv[2];if(!/^\d{2}$/.test(batch??''))throw Error('Use a two-digit batch number');
const base=`content/town-profiles/batch-${batch}`;const docs=`docs/town-profiles/batch-${batch}`;const privateDir=`.wrangler/town-profiles/batch-${batch}`;
const raw=readFileSync(`${base}.manifest.json`,'utf8');const m=JSON.parse(raw) as {updates:ContentPageRecord[];sources:SourceRecord[];sourceLinks:ContentSourceLink[];relationships:ContentRelationship[]};
const queue=JSON.parse(readFileSync('docs/town-profiles/QUEUE.json','utf8')).towns as {id:string;batch:number}[];const expected=queue.filter(t=>t.batch===Number(batch)).map(t=>t.id);if(!expected.length||m.updates.length!==expected.length||new Set(m.updates.map(p=>p.id)).size!==expected.length||m.updates.some(p=>p.page_type!=='LOCATION'||!expected.includes(p.primary_location_id!)))throw Error('Wrong batch scope');
if(Number(batch)>1){const previous=String(Number(batch)-1).padStart(2,'0');const evidence=JSON.parse(readFileSync(`docs/town-profiles/batch-${previous}.live.json`,'utf8'));if(evidence.errors.length||evidence.count!==queue.filter(t=>t.batch===Number(previous)).length)throw Error('Previous batch not verified');}
const hash=createHash('sha256').update(raw).digest('hex');if(hash!==JSON.parse(readFileSync(`${docs}.review.json`,'utf8')).sha256)throw Error('Unreviewed manifest');
if(new URL(process.env.NEXT_PUBLIC_SUPABASE_URL!).hostname!=='hfzzudrukeshkzsqhwsg.supabase.co')throw Error('Wrong project');
const db=getSupabaseAdmin();const live=await db.from('content_pages').select('*').in('id',m.updates.map(p=>p.id));if(live.error||live.data.length!==m.updates.length)throw Error('Incomplete preflight');
for(const p of m.updates){if(!validateForPublication({page:p}).valid)throw Error('Invalid page');const old=live.data.find(r=>r.id===p.id);if(old.updated_at!==p.updated_at||old.status!=='PUBLISHED'||old.indexable)throw Error('Concurrent change: '+p.slug);}
console.log({preflight:'passed',updates:m.updates.length,newSources:m.sources.length,sha256:hash});if(!process.argv.includes('--apply'))process.exit(0);
const prefix=`${privateDir}/content`;if(existsSync(prefix+'-receipt.json'))throw Error('Prior receipt: inspect before resume');writeFileSync(prefix+'-release-before.json',JSON.stringify(live.data),{flag:'wx',mode:0o600});
const receipt:{sha256:string;started:string;intent:unknown;writes:unknown[];completed?:string}={sha256:hash,started:new Date().toISOString(),intent:null,writes:[]};const save=()=>writeFileSync(prefix+'-receipt.json',JSON.stringify(receipt,null,2),{mode:0o600});save();
for(const[table,rows]of[['sources',m.sources],['content_sources',m.sourceLinks],['content_relationships',m.relationships]]as const){if(!rows.length)continue;receipt.intent={table,count:rows.length};save();const r=await db.from(table).insert(rows as Record<string,unknown>[]).select();if(r.error||r.data.length!==rows.length)throw Error('Failed or uncertain '+table+':'+r.error?.code);receipt.writes.push({table,count:rows.length});receipt.intent=null;save();}
for(const p of m.updates){receipt.intent={table:'content_pages',id:p.id};save();const stamp=new Date().toISOString();const r=await db.from('content_pages').update({sections:p.sections,direct_answer:p.direct_answer,meta_description:p.meta_description,indexable:p.indexable,reviewed_by:p.reviewed_by,reviewed_at:stamp,last_reviewed_at:stamp,updated_at:stamp}).eq('id',p.id).eq('updated_at',p.updated_at).select('id,updated_at');if(r.error||r.data.length!==1)throw Error('Failed/concurrent '+p.slug);receipt.writes.push(r.data[0]);receipt.intent=null;save();}receipt.completed=new Date().toISOString();save();console.log({completed:receipt.completed,writes:receipt.writes.length});
