import Link from 'next/link';
import {AdminPageHeader} from '@/components/admin/AdminPageHeader';
import {loadVendorSignups} from '@/lib/vendor-signup/admin';
import {formatAdminDateTime} from '@/lib/admin/format';
import styles from '@/components/admin/admin.module.css';
export default async function SignupInbox({searchParams}:{searchParams:Promise<{view?:string;page?:string}>}){
 const params=await searchParams,all=params.view==='all',rows=await loadVendorSignups(!all);
 const requested=Number(params.page),pages=Math.max(1,Math.ceil(rows.length/30));const page=Number.isSafeInteger(requested)&&requested>0?Math.min(requested,pages):1;
 return <><AdminPageHeader title="Vendor signups" description="Review self-submitted business details, check for duplicates, then create or link a vendor." actions={<Link className={styles.secondaryButton} href="/admin/vendors">All vendors</Link>}/><nav className={styles.filters}><Link href="/admin/vendors/signups" aria-current={!all?'page':undefined}>Pending</Link><Link href="/admin/vendors/signups?view=all" aria-current={all?'page':undefined}>All signups</Link></nav>{!rows.length?<p className={styles.empty}>{process.env.ENABLE_VENDOR_SIGNUP==='true'?'No signups in this view.':'Online vendor signup is currently disabled.'}</p>:<div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Business</th><th>Coverage</th><th>Status</th><th>Received · UTC</th></tr></thead><tbody>{rows.slice((page-1)*30,page*30).map(row=><tr key={row.id}><td data-label="Business"><Link href={`/admin/vendors/signups/${row.id}`}>{row.payload.businessName}</Link><p>{row.payload.email}</p></td><td data-label="Coverage">{row.payload.serviceIds.length} services · {row.payload.locationIds.length} towns</td><td data-label="Status">{row.status}</td><td data-label="Received">{formatAdminDateTime(row.created_at)}</td></tr>)}</tbody></table></div>}<nav className={styles.filters} aria-label="Signup pages">{page>1&&<Link href={`?view=${all?'all':'pending'}&page=${page-1}`}>Previous</Link>}<span>Page {page} of {pages} · {rows.length} signups</span>{page<pages&&<Link href={`?view=${all?'all':'pending'}&page=${page+1}`}>Next</Link>}</nav></>;
}
