-- Owner-authorized North Jersey request geography. No vendor coverage or activation.
-- Preserve all legacy IDs; Chatham Borough and Township get distinct classification IDs.
insert into public.locations (id, name, slug, state) values
 ('allendale', 'Allendale', 'allendale', 'NJ'),
 ('alpine', 'Alpine', 'alpine', 'NJ'),
 ('bergenfield', 'Bergenfield', 'bergenfield', 'NJ'),
 ('bogota', 'Bogota', 'bogota', 'NJ'),
 ('carlstadt', 'Carlstadt', 'carlstadt', 'NJ'),
 ('cliffside-park', 'Cliffside Park', 'cliffside-park', 'NJ'),
 ('closter', 'Closter', 'closter', 'NJ'),
 ('cresskill', 'Cresskill', 'cresskill', 'NJ'),
 ('demarest', 'Demarest', 'demarest', 'NJ'),
 ('dumont', 'Dumont', 'dumont', 'NJ'),
 ('east-rutherford', 'East Rutherford', 'east-rutherford', 'NJ'),
 ('edgewater', 'Edgewater', 'edgewater', 'NJ'),
 ('elmwood-park', 'Elmwood Park', 'elmwood-park', 'NJ'),
 ('emerson', 'Emerson', 'emerson', 'NJ'),
 ('englewood', 'Englewood', 'englewood', 'NJ'),
 ('englewood-cliffs', 'Englewood Cliffs', 'englewood-cliffs', 'NJ'),
 ('fair-lawn', 'Fair Lawn', 'fair-lawn', 'NJ'),
 ('fairview', 'Fairview', 'fairview', 'NJ'),
 ('fort-lee', 'Fort Lee', 'fort-lee', 'NJ'),
 ('franklin-lakes', 'Franklin Lakes', 'franklin-lakes', 'NJ'),
 ('garfield', 'Garfield', 'garfield', 'NJ'),
 ('glen-rock', 'Glen Rock', 'glen-rock', 'NJ'),
 ('hackensack', 'Hackensack', 'hackensack', 'NJ'),
 ('harrington-park', 'Harrington Park', 'harrington-park', 'NJ'),
 ('hasbrouck-heights', 'Hasbrouck Heights', 'hasbrouck-heights', 'NJ'),
 ('haworth', 'Haworth', 'haworth', 'NJ'),
 ('hillsdale', 'Hillsdale', 'hillsdale', 'NJ'),
 ('ho-ho-kus', 'Ho-Ho-Kus', 'ho-ho-kus', 'NJ'),
 ('leonia', 'Leonia', 'leonia', 'NJ'),
 ('little-ferry', 'Little Ferry', 'little-ferry', 'NJ'),
 ('lodi', 'Lodi', 'lodi', 'NJ'),
 ('lyndhurst', 'Lyndhurst', 'lyndhurst', 'NJ'),
 ('mahwah', 'Mahwah', 'mahwah', 'NJ'),
 ('maywood', 'Maywood', 'maywood', 'NJ'),
 ('midland-park', 'Midland Park', 'midland-park', 'NJ'),
 ('montvale', 'Montvale', 'montvale', 'NJ'),
 ('moonachie', 'Moonachie', 'moonachie', 'NJ'),
 ('new-milford', 'New Milford', 'new-milford', 'NJ'),
 ('north-arlington', 'North Arlington', 'north-arlington', 'NJ'),
 ('northvale', 'Northvale', 'northvale', 'NJ'),
 ('norwood', 'Norwood', 'norwood', 'NJ'),
 ('oakland', 'Oakland', 'oakland', 'NJ'),
 ('old-tappan', 'Old Tappan', 'old-tappan', 'NJ'),
 ('oradell', 'Oradell', 'oradell', 'NJ'),
 ('palisades-park', 'Palisades Park', 'palisades-park', 'NJ'),
 ('paramus', 'Paramus', 'paramus', 'NJ'),
 ('park-ridge', 'Park Ridge', 'park-ridge', 'NJ'),
 ('ramsey', 'Ramsey', 'ramsey', 'NJ'),
 ('ridgefield', 'Ridgefield', 'ridgefield', 'NJ'),
 ('ridgefield-park', 'Ridgefield Park', 'ridgefield-park', 'NJ'),
 ('ridgewood', 'Ridgewood', 'ridgewood', 'NJ'),
 ('river-edge', 'River Edge', 'river-edge', 'NJ'),
 ('river-vale', 'River Vale', 'river-vale', 'NJ'),
 ('rochelle-park', 'Rochelle Park', 'rochelle-park', 'NJ'),
 ('rockleigh', 'Rockleigh', 'rockleigh', 'NJ'),
 ('rutherford', 'Rutherford', 'rutherford', 'NJ'),
 ('saddle-brook', 'Saddle Brook', 'saddle-brook', 'NJ'),
 ('saddle-river', 'Saddle River', 'saddle-river', 'NJ'),
 ('south-hackensack', 'South Hackensack', 'south-hackensack', 'NJ'),
 ('teaneck', 'Teaneck', 'teaneck', 'NJ'),
 ('tenafly', 'Tenafly', 'tenafly', 'NJ'),
 ('teterboro', 'Teterboro', 'teterboro', 'NJ'),
 ('upper-saddle-river', 'Upper Saddle River', 'upper-saddle-river', 'NJ'),
 ('waldwick', 'Waldwick', 'waldwick', 'NJ'),
 ('wallington', 'Wallington', 'wallington', 'NJ'),
 ('washington-township-bergen', 'Washington Township', 'washington-township-bergen', 'NJ'),
 ('westwood', 'Westwood', 'westwood', 'NJ'),
 ('woodcliff-lake', 'Woodcliff Lake', 'woodcliff-lake', 'NJ'),
 ('wood-ridge', 'Wood-Ridge', 'wood-ridge', 'NJ'),
 ('wyckoff', 'Wyckoff', 'wyckoff', 'NJ'),
 ('belleville', 'Belleville', 'belleville', 'NJ'),
 ('bloomfield', 'Bloomfield', 'bloomfield', 'NJ'),
 ('caldwell', 'Caldwell', 'caldwell', 'NJ'),
 ('cedar-grove', 'Cedar Grove', 'cedar-grove', 'NJ'),
 ('east-orange', 'East Orange', 'east-orange', 'NJ'),
 ('essex-fells', 'Essex Fells', 'essex-fells', 'NJ'),
 ('fairfield', 'Fairfield', 'fairfield', 'NJ'),
 ('glen-ridge', 'Glen Ridge', 'glen-ridge', 'NJ'),
 ('irvington', 'Irvington', 'irvington', 'NJ'),
 ('maplewood', 'Maplewood', 'maplewood', 'NJ'),
 ('millburn', 'Millburn', 'millburn', 'NJ'),
 ('montclair', 'Montclair', 'montclair', 'NJ'),
 ('newark', 'Newark', 'newark', 'NJ'),
 ('north-caldwell', 'North Caldwell', 'north-caldwell', 'NJ'),
 ('nutley', 'Nutley', 'nutley', 'NJ'),
 ('orange', 'Orange', 'orange', 'NJ'),
 ('roseland', 'Roseland', 'roseland', 'NJ'),
 ('south-orange', 'South Orange', 'south-orange', 'NJ'),
 ('verona', 'Verona', 'verona', 'NJ'),
 ('west-caldwell', 'West Caldwell', 'west-caldwell', 'NJ'),
 ('west-orange', 'West Orange', 'west-orange', 'NJ'),
 ('bayonne', 'Bayonne', 'bayonne', 'NJ'),
 ('east-newark', 'East Newark', 'east-newark', 'NJ'),
 ('guttenberg', 'Guttenberg', 'guttenberg', 'NJ'),
 ('harrison', 'Harrison', 'harrison', 'NJ'),
 ('hoboken', 'Hoboken', 'hoboken', 'NJ'),
 ('jersey-city', 'Jersey City', 'jersey-city', 'NJ'),
 ('kearny', 'Kearny', 'kearny', 'NJ'),
 ('north-bergen', 'North Bergen', 'north-bergen', 'NJ'),
 ('secaucus', 'Secaucus', 'secaucus', 'NJ'),
 ('union-city', 'Union City', 'union-city', 'NJ'),
 ('weehawken', 'Weehawken', 'weehawken', 'NJ'),
 ('west-new-york', 'West New York', 'west-new-york', 'NJ'),
 ('boonton', 'Boonton', 'boonton', 'NJ'),
 ('boonton-township', 'Boonton Township', 'boonton-township', 'NJ'),
 ('butler', 'Butler', 'butler', 'NJ'),
 ('chatham-borough', 'Chatham Borough', 'chatham-borough', 'NJ'),
 ('chatham-township', 'Chatham Township', 'chatham-township', 'NJ'),
 ('chester-borough', 'Chester Borough', 'chester-borough', 'NJ'),
 ('chester-township', 'Chester Township', 'chester-township', 'NJ'),
 ('denville', 'Denville', 'denville', 'NJ'),
 ('dover', 'Dover', 'dover', 'NJ'),
 ('harding', 'Harding', 'harding', 'NJ'),
 ('jefferson-township', 'Jefferson Township', 'jefferson-township', 'NJ'),
 ('kinnelon', 'Kinnelon', 'kinnelon', 'NJ'),
 ('lincoln-park', 'Lincoln Park', 'lincoln-park', 'NJ'),
 ('long-hill-township', 'Long Hill Township', 'long-hill-township', 'NJ'),
 ('mendham-borough', 'Mendham Borough', 'mendham-borough', 'NJ'),
 ('mendham-township', 'Mendham Township', 'mendham-township', 'NJ'),
 ('mine-hill', 'Mine Hill', 'mine-hill', 'NJ'),
 ('montville', 'Montville', 'montville', 'NJ'),
 ('morris-plains', 'Morris Plains', 'morris-plains', 'NJ'),
 ('mount-arlington', 'Mount Arlington', 'mount-arlington', 'NJ'),
 ('mount-olive', 'Mount Olive', 'mount-olive', 'NJ'),
 ('mountain-lakes', 'Mountain Lakes', 'mountain-lakes', 'NJ'),
 ('netcong', 'Netcong', 'netcong', 'NJ'),
 ('parsippany-troy-hills', 'Parsippany-Troy Hills', 'parsippany-troy-hills', 'NJ'),
 ('pequannock', 'Pequannock', 'pequannock', 'NJ'),
 ('randolph', 'Randolph', 'randolph', 'NJ'),
 ('riverdale', 'Riverdale', 'riverdale', 'NJ'),
 ('rockaway-borough', 'Rockaway Borough', 'rockaway-borough', 'NJ'),
 ('rockaway-township', 'Rockaway Township', 'rockaway-township', 'NJ'),
 ('roxbury', 'Roxbury', 'roxbury', 'NJ'),
 ('victory-gardens', 'Victory Gardens', 'victory-gardens', 'NJ'),
 ('washington-township-morris', 'Washington Township', 'washington-township-morris', 'NJ'),
 ('wharton', 'Wharton', 'wharton', 'NJ'),
 ('bloomingdale', 'Bloomingdale', 'bloomingdale', 'NJ'),
 ('clifton', 'Clifton', 'clifton', 'NJ'),
 ('haledon', 'Haledon', 'haledon', 'NJ'),
 ('hawthorne', 'Hawthorne', 'hawthorne', 'NJ'),
 ('little-falls', 'Little Falls', 'little-falls', 'NJ'),
 ('north-haledon', 'North Haledon', 'north-haledon', 'NJ'),
 ('passaic', 'Passaic', 'passaic', 'NJ'),
 ('paterson', 'Paterson', 'paterson', 'NJ'),
 ('pompton-lakes', 'Pompton Lakes', 'pompton-lakes', 'NJ'),
 ('prospect-park', 'Prospect Park', 'prospect-park', 'NJ'),
 ('ringwood', 'Ringwood', 'ringwood', 'NJ'),
 ('totowa', 'Totowa', 'totowa', 'NJ'),
 ('wanaque', 'Wanaque', 'wanaque', 'NJ'),
 ('wayne', 'Wayne', 'wayne', 'NJ'),
 ('west-milford', 'West Milford', 'west-milford', 'NJ'),
 ('woodland-park', 'Woodland Park', 'woodland-park', 'NJ'),
 ('andover-borough', 'Andover Borough', 'andover-borough', 'NJ'),
 ('andover-township', 'Andover Township', 'andover-township', 'NJ'),
 ('branchville', 'Branchville', 'branchville', 'NJ'),
 ('byram', 'Byram', 'byram', 'NJ'),
 ('frankford', 'Frankford', 'frankford', 'NJ'),
 ('franklin-borough', 'Franklin Borough', 'franklin-borough', 'NJ'),
 ('fredon', 'Fredon', 'fredon', 'NJ'),
 ('green-township', 'Green Township', 'green-township', 'NJ'),
 ('hamburg', 'Hamburg', 'hamburg', 'NJ'),
 ('hampton-township', 'Hampton Township', 'hampton-township', 'NJ'),
 ('hardyston', 'Hardyston', 'hardyston', 'NJ'),
 ('hopatcong', 'Hopatcong', 'hopatcong', 'NJ'),
 ('lafayette', 'Lafayette', 'lafayette', 'NJ'),
 ('montague', 'Montague', 'montague', 'NJ'),
 ('newton', 'Newton', 'newton', 'NJ'),
 ('ogdensburg', 'Ogdensburg', 'ogdensburg', 'NJ'),
 ('sandyston', 'Sandyston', 'sandyston', 'NJ'),
 ('sparta', 'Sparta', 'sparta', 'NJ'),
 ('stanhope', 'Stanhope', 'stanhope', 'NJ'),
 ('stillwater', 'Stillwater', 'stillwater', 'NJ'),
 ('sussex', 'Sussex', 'sussex', 'NJ'),
 ('vernon', 'Vernon', 'vernon', 'NJ'),
 ('walpack', 'Walpack', 'walpack', 'NJ'),
 ('wantage', 'Wantage', 'wantage', 'NJ'),
 ('berkeley-heights', 'Berkeley Heights', 'berkeley-heights', 'NJ'),
 ('clark', 'Clark', 'clark', 'NJ'),
 ('cranford', 'Cranford', 'cranford', 'NJ'),
 ('elizabeth', 'Elizabeth', 'elizabeth', 'NJ'),
 ('fanwood', 'Fanwood', 'fanwood', 'NJ'),
 ('garwood', 'Garwood', 'garwood', 'NJ'),
 ('hillside', 'Hillside', 'hillside', 'NJ'),
 ('kenilworth', 'Kenilworth', 'kenilworth', 'NJ'),
 ('linden', 'Linden', 'linden', 'NJ'),
 ('mountainside', 'Mountainside', 'mountainside', 'NJ'),
 ('new-providence', 'New Providence', 'new-providence', 'NJ'),
 ('plainfield', 'Plainfield', 'plainfield', 'NJ'),
 ('rahway', 'Rahway', 'rahway', 'NJ'),
 ('roselle', 'Roselle', 'roselle', 'NJ'),
 ('roselle-park', 'Roselle Park', 'roselle-park', 'NJ'),
 ('scotch-plains', 'Scotch Plains', 'scotch-plains', 'NJ'),
 ('springfield', 'Springfield', 'springfield', 'NJ'),
 ('union-township', 'Union Township', 'union-township', 'NJ'),
 ('westfield', 'Westfield', 'westfield', 'NJ'),
 ('winfield', 'Winfield', 'winfield', 'NJ'),
 ('allamuchy', 'Allamuchy', 'allamuchy', 'NJ'),
 ('alpha', 'Alpha', 'alpha', 'NJ'),
 ('belvidere', 'Belvidere', 'belvidere', 'NJ'),
 ('blairstown', 'Blairstown', 'blairstown', 'NJ'),
 ('franklin-township', 'Franklin Township', 'franklin-township', 'NJ'),
 ('frelinghuysen', 'Frelinghuysen', 'frelinghuysen', 'NJ'),
 ('greenwich-township', 'Greenwich Township', 'greenwich-township', 'NJ'),
 ('hackettstown', 'Hackettstown', 'hackettstown', 'NJ'),
 ('hardwick', 'Hardwick', 'hardwick', 'NJ'),
 ('harmony', 'Harmony', 'harmony', 'NJ'),
 ('hope', 'Hope', 'hope', 'NJ'),
 ('independence', 'Independence', 'independence', 'NJ'),
 ('knowlton', 'Knowlton', 'knowlton', 'NJ'),
 ('liberty-township', 'Liberty Township', 'liberty-township', 'NJ'),
 ('lopatcong', 'Lopatcong', 'lopatcong', 'NJ'),
 ('mansfield-township', 'Mansfield Township', 'mansfield-township', 'NJ'),
 ('oxford', 'Oxford', 'oxford', 'NJ'),
 ('phillipsburg', 'Phillipsburg', 'phillipsburg', 'NJ'),
 ('pohatcong', 'Pohatcong', 'pohatcong', 'NJ'),
 ('washington-borough', 'Washington Borough', 'washington-borough', 'NJ'),
 ('washington-township-warren', 'Washington Township', 'washington-township-warren', 'NJ'),
 ('white-township', 'White Township', 'white-township', 'NJ')
on conflict (id) do nothing;
